/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

IF OBJECT_ID('section_person_nicknames', 'U') IS NOT NULL
  DROP TABLE [section_person_nicknames];
GO

IF OBJECT_ID('section_person', 'U') IS NOT NULL
  DROP TABLE [section_person];
GO

CREATE TABLE [section_person] (
  [id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
  [first] VARCHAR(512) NOT NULL,
  [last] VARCHAR(512) NOT NULL,
  [bio] VARCHAR(512) NOT NULL);
GO

CREATE TABLE [section_person_nicknames] (
  [object_id] BIGINT NOT NULL,
  [index] BIGINT NOT NULL,
  [value] VARCHAR(512) NOT NULL,
  CONSTRAINT [section_person_nicknames_object_id_fk]
    FOREIGN KEY ([object_id])
    REFERENCES [section_person] ([id])
    ON DELETE CASCADE);
GO

CREATE INDEX [object_id_i]
  ON [section_person_nicknames] ([object_id]);
GO

CREATE INDEX [index_i]
  ON [section_person_nicknames] ([index]);
GO

