// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#define ODB_MSSQL_QUERY_COLUMNS_DEF
#include "ClosingPrice-odb-mssql.hxx"
#undef ODB_MSSQL_QUERY_COLUMNS_DEF

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/function-table.hxx>

#include <odb/mssql/traits.hxx>
#include <odb/mssql/database.hxx>
#include <odb/mssql/transaction.hxx>
#include <odb/mssql/connection.hxx>
#include <odb/mssql/statement.hxx>
#include <odb/mssql/statement-cache.hxx>
#include <odb/mssql/simple-object-statements.hxx>
#include <odb/mssql/container-statements.hxx>
#include <odb/mssql/exceptions.hxx>
#include <odb/mssql/simple-object-result.hxx>

namespace odb
{
  // id
  //

  void access::composite_value_traits< ::id, id_mssql >::
  bind (mssql::bind* b,
        image_type& i,
        mssql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (b);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mssql;

    std::size_t n (0);
    ODB_POTENTIALLY_UNUSED (n);

    // Date
    //
    b[n].type = mssql::bind::datetime;
    b[n].buffer = &i.Date_value;
    b[n].size_ind = &i.Date_size_ind;
    b[n].capacity = 3;
    n++;

    // Estee_ID
    //
    b[n].type = mssql::bind::string;
    b[n].buffer = &i.Estee_ID_value;
    b[n].size_ind = &i.Estee_ID_size_ind;
    b[n].capacity = static_cast<SQLLEN> (sizeof (i.Estee_ID_value));
    n++;
  }

  void access::composite_value_traits< ::id, id_mssql >::
  init (image_type& i,
        const value_type& o,
        mssql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mssql;

    // Date
    //
    {
      ::boost::posix_time::ptime const& v =
        o.Date;

      bool is_null (true);
      mssql::value_traits<
          ::boost::posix_time::ptime,
          mssql::id_datetime >::set_image (
        i.Date_value, 3, is_null, v);
      i.Date_size_ind = is_null ? SQL_NULL_DATA : 0;
    }

    // Estee_ID
    //
    {
      ::std::string const& v =
        o.Estee_ID;

      bool is_null (false);
      std::size_t size (0);
      mssql::value_traits<
          ::std::string,
          mssql::id_string >::set_image (
        i.Estee_ID_value,
        sizeof (i.Estee_ID_value) - 1,
        size,
        is_null,
        v);
      i.Estee_ID_size_ind =
        is_null ? SQL_NULL_DATA : static_cast<SQLLEN> (size);
    }
  }

  void access::composite_value_traits< ::id, id_mssql >::
  init (value_type& o,
        const image_type&  i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // Date
    //
    {
      ::boost::posix_time::ptime& v =
        o.Date;

      mssql::value_traits<
          ::boost::posix_time::ptime,
          mssql::id_datetime >::set_value (
        v,
        i.Date_value,
        i.Date_size_ind == SQL_NULL_DATA);
    }

    // Estee_ID
    //
    {
      ::std::string& v =
        o.Estee_ID;

      mssql::value_traits<
          ::std::string,
          mssql::id_string >::set_value (
        v,
        i.Estee_ID_value,
        static_cast<std::size_t> (i.Estee_ID_size_ind),
        i.Estee_ID_size_ind == SQL_NULL_DATA);
    }
  }

  // closingPrice
  //

  template struct query_columns<
    ::closingPrice,
    id_mssql,
    access::object_traits_impl< ::closingPrice, id_mssql > >;

  struct access::object_traits_impl< ::closingPrice, id_mssql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      mssql::connection&,
      image_type&,
      id_image_type&,
      mssql::binding&,
      mssql::binding&)
    {
    }
  };

  access::object_traits_impl< ::closingPrice, id_mssql >::id_type
  access::object_traits_impl< ::closingPrice, id_mssql >::
  id (const image_type& i)
  {
    mssql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      composite_value_traits< ::id, id_mssql >::init (
        id,
        i._id_value,
        db);
    }

    return id;
  }

  void access::object_traits_impl< ::closingPrice, id_mssql >::
  bind (mssql::bind* b,
        image_type& i,
        mssql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mssql;

    std::size_t n (0);

    // Open_Interest
    //
    b[n].type = mssql::bind::float8;
    b[n].buffer = &i.Open_Interest_value;
    b[n].size_ind = &i.Open_Interest_size_ind;
    b[n].capacity = 53;
    n++;

    // Settlement_price
    //
    b[n].type = mssql::bind::float8;
    b[n].buffer = &i.Settlement_price_value;
    b[n].size_ind = &i.Settlement_price_size_ind;
    b[n].capacity = 53;
    n++;

    // Open_Price
    //
    b[n].type = mssql::bind::float8;
    b[n].buffer = &i.Open_Price_value;
    b[n].size_ind = &i.Open_Price_size_ind;
    b[n].capacity = 53;
    n++;

    // High_Price
    //
    b[n].type = mssql::bind::float8;
    b[n].buffer = &i.High_Price_value;
    b[n].size_ind = &i.High_Price_size_ind;
    b[n].capacity = 53;
    n++;

    // Low_Price
    //
    b[n].type = mssql::bind::float8;
    b[n].buffer = &i.Low_Price_value;
    b[n].size_ind = &i.Low_Price_size_ind;
    b[n].capacity = 53;
    n++;

    // Close_Price
    //
    b[n].type = mssql::bind::float8;
    b[n].buffer = &i.Close_Price_value;
    b[n].size_ind = &i.Close_Price_size_ind;
    b[n].capacity = 53;
    n++;

    // Volume
    //
    b[n].type = mssql::bind::float8;
    b[n].buffer = &i.Volume_value;
    b[n].size_ind = &i.Volume_size_ind;
    b[n].capacity = 53;
    n++;

    // Net_Traded_Val
    //
    b[n].type = mssql::bind::float8;
    b[n].buffer = &i.Net_Traded_Val_value;
    b[n].size_ind = &i.Net_Traded_Val_size_ind;
    b[n].capacity = 53;
    n++;

    // Trades
    //
    b[n].type = mssql::bind::int_;
    b[n].buffer = &i.Trades_value;
    b[n].size_ind = &i.Trades_size_ind;
    n++;

    // Source
    //
    b[n].type = mssql::bind::string;
    b[n].buffer = &i.Source_value;
    b[n].size_ind = &i.Source_size_ind;
    b[n].capacity = static_cast<SQLLEN> (sizeof (i.Source_value));
    n++;

    // _id
    //
    if (sk != statement_update)
    {
      composite_value_traits< ::id, id_mssql >::bind (
        b + n, i._id_value, sk);
      n += 2UL;
    }
  }

  void access::object_traits_impl< ::closingPrice, id_mssql >::
  bind (mssql::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    mssql::statement_kind sk (mssql::statement_select);
    composite_value_traits< ::id, id_mssql >::bind (
      b + n, i.id_value, sk);
  }

  void access::object_traits_impl< ::closingPrice, id_mssql >::
  init (image_type& i,
        const object_type& o,
        mssql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mssql;

    if (i.change_callback_.callback != 0)
      (i.change_callback_.callback) (i.change_callback_.context);

    // Open_Interest
    //
    {
      double const& v =
        o.Open_Interest;

      bool is_null (false);
      mssql::value_traits<
          double,
          mssql::id_float8 >::set_image (
        i.Open_Interest_value, is_null, v);
      i.Open_Interest_size_ind = is_null ? SQL_NULL_DATA : 0;
    }

    // Settlement_price
    //
    {
      double const& v =
        o.Settlement_price;

      bool is_null (false);
      mssql::value_traits<
          double,
          mssql::id_float8 >::set_image (
        i.Settlement_price_value, is_null, v);
      i.Settlement_price_size_ind = is_null ? SQL_NULL_DATA : 0;
    }

    // Open_Price
    //
    {
      double const& v =
        o.Open_Price;

      bool is_null (false);
      mssql::value_traits<
          double,
          mssql::id_float8 >::set_image (
        i.Open_Price_value, is_null, v);
      i.Open_Price_size_ind = is_null ? SQL_NULL_DATA : 0;
    }

    // High_Price
    //
    {
      double const& v =
        o.High_Price;

      bool is_null (false);
      mssql::value_traits<
          double,
          mssql::id_float8 >::set_image (
        i.High_Price_value, is_null, v);
      i.High_Price_size_ind = is_null ? SQL_NULL_DATA : 0;
    }

    // Low_Price
    //
    {
      double const& v =
        o.Low_Price;

      bool is_null (false);
      mssql::value_traits<
          double,
          mssql::id_float8 >::set_image (
        i.Low_Price_value, is_null, v);
      i.Low_Price_size_ind = is_null ? SQL_NULL_DATA : 0;
    }

    // Close_Price
    //
    {
      double const& v =
        o.Close_Price;

      bool is_null (false);
      mssql::value_traits<
          double,
          mssql::id_float8 >::set_image (
        i.Close_Price_value, is_null, v);
      i.Close_Price_size_ind = is_null ? SQL_NULL_DATA : 0;
    }

    // Volume
    //
    {
      double const& v =
        o.Volume;

      bool is_null (false);
      mssql::value_traits<
          double,
          mssql::id_float8 >::set_image (
        i.Volume_value, is_null, v);
      i.Volume_size_ind = is_null ? SQL_NULL_DATA : 0;
    }

    // Net_Traded_Val
    //
    {
      double const& v =
        o.Net_Traded_Val;

      bool is_null (false);
      mssql::value_traits<
          double,
          mssql::id_float8 >::set_image (
        i.Net_Traded_Val_value, is_null, v);
      i.Net_Traded_Val_size_ind = is_null ? SQL_NULL_DATA : 0;
    }

    // Trades
    //
    {
      int const& v =
        o.Trades;

      bool is_null (false);
      mssql::value_traits<
          int,
          mssql::id_int >::set_image (
        i.Trades_value, is_null, v);
      i.Trades_size_ind = is_null ? SQL_NULL_DATA : 0;
    }

    // Source
    //
    {
      ::std::string const& v =
        o.Source;

      bool is_null (false);
      std::size_t size (0);
      mssql::value_traits<
          ::std::string,
          mssql::id_string >::set_image (
        i.Source_value,
        sizeof (i.Source_value) - 1,
        size,
        is_null,
        v);
      i.Source_size_ind =
        is_null ? SQL_NULL_DATA : static_cast<SQLLEN> (size);
    }

    // _id
    //
    if (sk == statement_insert)
    {
      ::id const& v =
        o._id;

      composite_value_traits< ::id, id_mssql >::init (
        i._id_value,
        v,
        sk);
    }
  }

  void access::object_traits_impl< ::closingPrice, id_mssql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // Open_Interest
    //
    {
      double& v =
        o.Open_Interest;

      mssql::value_traits<
          double,
          mssql::id_float8 >::set_value (
        v,
        i.Open_Interest_value,
        i.Open_Interest_size_ind == SQL_NULL_DATA);
    }

    // Settlement_price
    //
    {
      double& v =
        o.Settlement_price;

      mssql::value_traits<
          double,
          mssql::id_float8 >::set_value (
        v,
        i.Settlement_price_value,
        i.Settlement_price_size_ind == SQL_NULL_DATA);
    }

    // Open_Price
    //
    {
      double& v =
        o.Open_Price;

      mssql::value_traits<
          double,
          mssql::id_float8 >::set_value (
        v,
        i.Open_Price_value,
        i.Open_Price_size_ind == SQL_NULL_DATA);
    }

    // High_Price
    //
    {
      double& v =
        o.High_Price;

      mssql::value_traits<
          double,
          mssql::id_float8 >::set_value (
        v,
        i.High_Price_value,
        i.High_Price_size_ind == SQL_NULL_DATA);
    }

    // Low_Price
    //
    {
      double& v =
        o.Low_Price;

      mssql::value_traits<
          double,
          mssql::id_float8 >::set_value (
        v,
        i.Low_Price_value,
        i.Low_Price_size_ind == SQL_NULL_DATA);
    }

    // Close_Price
    //
    {
      double& v =
        o.Close_Price;

      mssql::value_traits<
          double,
          mssql::id_float8 >::set_value (
        v,
        i.Close_Price_value,
        i.Close_Price_size_ind == SQL_NULL_DATA);
    }

    // Volume
    //
    {
      double& v =
        o.Volume;

      mssql::value_traits<
          double,
          mssql::id_float8 >::set_value (
        v,
        i.Volume_value,
        i.Volume_size_ind == SQL_NULL_DATA);
    }

    // Net_Traded_Val
    //
    {
      double& v =
        o.Net_Traded_Val;

      mssql::value_traits<
          double,
          mssql::id_float8 >::set_value (
        v,
        i.Net_Traded_Val_value,
        i.Net_Traded_Val_size_ind == SQL_NULL_DATA);
    }

    // Trades
    //
    {
      int& v =
        o.Trades;

      mssql::value_traits<
          int,
          mssql::id_int >::set_value (
        v,
        i.Trades_value,
        i.Trades_size_ind == SQL_NULL_DATA);
    }

    // Source
    //
    {
      ::std::string& v =
        o.Source;

      mssql::value_traits<
          ::std::string,
          mssql::id_string >::set_value (
        v,
        i.Source_value,
        static_cast<std::size_t> (i.Source_size_ind),
        i.Source_size_ind == SQL_NULL_DATA);
    }

    // _id
    //
    {
      ::id& v =
        o._id;

      composite_value_traits< ::id, id_mssql >::init (
        v,
        i._id_value,
        db);
    }
  }

  void access::object_traits_impl< ::closingPrice, id_mssql >::
  init (id_image_type& i, const id_type& id)
  {
    mssql::statement_kind sk (mssql::statement_select);
    {
      composite_value_traits< ::id, id_mssql >::init (
        i.id_value,
        id,
        sk);
    }
  }

  const char access::object_traits_impl< ::closingPrice, id_mssql >::persist_statement[] =
  "INSERT INTO [closingPrice] "
  "([Open_Interest], "
  "[Settlement_price], "
  "[Open_Price], "
  "[High_Price], "
  "[Low_Price], "
  "[Close_Price], "
  "[Volume], "
  "[Net_Traded_Val], "
  "[Trades], "
  "[Source], "
  "[Date], "
  "[Estee_ID]) "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::closingPrice, id_mssql >::find_statement[] =
  "SELECT "
  "[closingPrice].[Open_Interest], "
  "[closingPrice].[Settlement_price], "
  "[closingPrice].[Open_Price], "
  "[closingPrice].[High_Price], "
  "[closingPrice].[Low_Price], "
  "[closingPrice].[Close_Price], "
  "[closingPrice].[Volume], "
  "[closingPrice].[Net_Traded_Val], "
  "[closingPrice].[Trades], "
  "[closingPrice].[Source], "
  "[closingPrice].[Date], "
  "[closingPrice].[Estee_ID] "
  "FROM [closingPrice] "
  "WHERE [closingPrice].[Date]=? AND [closingPrice].[Estee_ID]=?";

  const char access::object_traits_impl< ::closingPrice, id_mssql >::update_statement[] =
  "UPDATE [closingPrice] "
  "SET "
  "[Open_Interest]=?, "
  "[Settlement_price]=?, "
  "[Open_Price]=?, "
  "[High_Price]=?, "
  "[Low_Price]=?, "
  "[Close_Price]=?, "
  "[Volume]=?, "
  "[Net_Traded_Val]=?, "
  "[Trades]=?, "
  "[Source]=? "
  "WHERE [Date]=? AND [Estee_ID]=?";

  const char access::object_traits_impl< ::closingPrice, id_mssql >::erase_statement[] =
  "DELETE FROM [closingPrice] "
  "WHERE [Date]=? AND [Estee_ID]=?";

  const char access::object_traits_impl< ::closingPrice, id_mssql >::query_statement[] =
  "SELECT "
  "[closingPrice].[Open_Interest], "
  "[closingPrice].[Settlement_price], "
  "[closingPrice].[Open_Price], "
  "[closingPrice].[High_Price], "
  "[closingPrice].[Low_Price], "
  "[closingPrice].[Close_Price], "
  "[closingPrice].[Volume], "
  "[closingPrice].[Net_Traded_Val], "
  "[closingPrice].[Trades], "
  "[closingPrice].[Source], "
  "[closingPrice].[Date], "
  "[closingPrice].[Estee_ID] "
  "FROM [closingPrice]";

  const char access::object_traits_impl< ::closingPrice, id_mssql >::erase_query_statement[] =
  "DELETE FROM [closingPrice]";

  const char access::object_traits_impl< ::closingPrice, id_mssql >::table_name[] =
  "[closingPrice]";

  void access::object_traits_impl< ::closingPrice, id_mssql >::
  persist (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mssql;

    mssql::connection& conn (
      mssql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    init (im, obj, statement_insert);

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::closingPrice, id_mssql >::
  persist (database& db,
           const object_type** objs,
           std::size_t n,
           multiple_exceptions& mex)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mssql;

    mssql::connection& conn (
      mssql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    for (std::size_t i (0); i != n; ++i)
    {
      const object_type& obj (*objs[i]);
      callback (db, obj, callback_event::pre_persist);
      init (sts.image (i), obj, statement_insert);
    }

    binding& imb (sts.insert_image_binding ());
    if (imb.version == 0)
    {
      bind (imb.bind, sts.image (), statement_insert);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    n = st.execute (n, mex);

    for (std::size_t i (0); i != n; ++i)
    {
      bool r (st.result (i));

      if (mex[i] != 0)
        continue;

      if (!r)
      {
        mex.insert (i, object_already_persistent ());
        continue;
      }

      if (mex.fatal ())
        continue;

      const object_type& obj (*objs[i]);

      callback (db,
                obj,
                callback_event::post_persist);
    }
  }

  void access::object_traits_impl< ::closingPrice, id_mssql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mssql;
    using mssql::update_statement;

    callback (db, obj, callback_event::pre_update);

    mssql::transaction& tr (mssql::transaction::current ());
    mssql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj._id);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    init (im, obj, statement_update);

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::closingPrice, id_mssql >::
  update (database& db,
          const object_type** objs,
          std::size_t n,
          multiple_exceptions& mex)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mssql;
    using mssql::update_statement;

    mssql::connection& conn (
      mssql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    for (std::size_t i (0); i != n; ++i)
    {
      const object_type& obj (*objs[i]);
      callback (db, obj, callback_event::pre_update);
      const id_type& id (
        obj._id);
      init (sts.id_image (i), id);
      init (sts.image (i), obj, statement_update);
    }

    binding& idb (sts.id_image_binding ());
    binding& imb (sts.update_image_binding ());

    bool u (false);
    if (imb.version == 0)
    {
      bind (imb.bind, sts.image (), statement_update);
      imb.version++;
      u = true;
    }

    if (idb.version == 0)
    {
      bind (idb.bind, sts.id_image ());
      idb.version++;

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    n = st.execute (n, mex);

    for (std::size_t i (0); i != n; ++i)
    {
      unsigned long long r (st.result (i));

      if (mex[i] != 0)
        continue;

      if (r != 1)
      {
        mex.insert (i,
                    (r == update_statement::result_unknown),
                    object_not_persistent ());
        continue;
      }

      if (mex.fatal ())
        continue;

      const object_type& obj (*objs[i]);
      callback (db, obj, callback_event::post_update);
      pointer_cache_traits::update (db, obj);
    }
  }

  void access::object_traits_impl< ::closingPrice, id_mssql >::
  erase (database& db, const id_type& id)
  {
    using namespace mssql;

    ODB_POTENTIALLY_UNUSED (db);

    mssql::connection& conn (
      mssql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  std::size_t access::object_traits_impl< ::closingPrice, id_mssql >::
  erase (database& db,
         const id_type** ids,
         std::size_t n,
         multiple_exceptions& mex)
  {
    using namespace mssql;

    ODB_POTENTIALLY_UNUSED (db);

    mssql::connection& conn (
      mssql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    for (std::size_t i (0); i != n; ++i)
      init (sts.id_image (i), *ids[i]);

    binding& idb (sts.id_image_binding ());
    if (idb.version == 0)
    {
      bind (idb.bind, sts.id_image ());
      idb.version++;
    }

    delete_statement& st (sts.erase_statement ());
    n = st.execute (n, mex);

    for (std::size_t i (0); i != n; ++i)
    {
      unsigned long long r (st.result (i));

      if (mex[i] != 0)
        continue;

      if (r != 1)
      {
        mex.insert (i,
                    (r == delete_statement::result_unknown),
                    object_not_persistent ());
        continue;
      }

      if (mex.fatal ())
        continue;
      pointer_cache_traits::erase (db, *ids[i]);
    }

    return n;
  }

  void access::object_traits_impl< ::closingPrice, id_mssql >::
  erase (database& db,
         const object_type** objs,
         std::size_t n,
         multiple_exceptions& mex)
  {
    id_type a[batch];
    const id_type* p[batch];

    for (std::size_t i (0); i != n; ++i)
    {
      const object_type& obj (*objs[i]);
      callback (db, obj, callback_event::pre_erase);
      a[i] = id (obj);
      p[i] = a + i;
    }

    n = erase (db, p, n, mex);

    if (mex.fatal ())
      return;

    for (std::size_t i (0); i != n; ++i)
    {
      if (mex[i] == 0)
        callback (db, *objs[i], callback_event::post_erase);
    }
  }

  access::object_traits_impl< ::closingPrice, id_mssql >::pointer_type
  access::object_traits_impl< ::closingPrice, id_mssql >::
  find (database& db, const id_type& id)
  {
    using namespace mssql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    mssql::connection& conn (
      mssql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    auto_result ar;

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();

      ar.set (sts.find_statement ());
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      st.stream_result ();
      ar.free ();
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::closingPrice, id_mssql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace mssql;

    mssql::connection& conn (
      mssql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    auto_result ar (st);
    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    st.stream_result ();
    ar.free ();
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::closingPrice, id_mssql >::
  reload (database& db, object_type& obj)
  {
    using namespace mssql;

    mssql::connection& conn (
      mssql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj._id);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    auto_result ar (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    st.stream_result ();
    ar.free ();
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::closingPrice, id_mssql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace mssql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r != select_statement::no_data)
    {
      ar.release ();
      return true;
    }
    else
      return false;
  }

  result< access::object_traits_impl< ::closingPrice, id_mssql >::object_type >
  access::object_traits_impl< ::closingPrice, id_mssql >::
  query (database&, const query_base_type& q)
  {
    using namespace mssql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    mssql::connection& conn (
      mssql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) mssql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  result< access::object_traits_impl< ::closingPrice, id_mssql >::object_type >
  access::object_traits_impl< ::closingPrice, id_mssql >::
  query (database& db, const odb::query_base& q)
  {
    return query (db, query_base_type (q));
  }

  unsigned long long access::object_traits_impl< ::closingPrice, id_mssql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace mssql;

    mssql::connection& conn (
      mssql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }

  unsigned long long access::object_traits_impl< ::closingPrice, id_mssql >::
  erase_query (database& db, const odb::query_base& q)
  {
    return erase_query (db, query_base_type (q));
  }

  static const
  access::object_traits_impl< ::closingPrice, id_common >::
  function_table_type function_table_closingPrice_ =
  {
    &access::object_traits_impl< ::closingPrice, id_mssql >::persist,
    &access::object_traits_impl< ::closingPrice, id_mssql >::find,
    &access::object_traits_impl< ::closingPrice, id_mssql >::find,
    &access::object_traits_impl< ::closingPrice, id_mssql >::reload,
    &access::object_traits_impl< ::closingPrice, id_mssql >::update,
    &access::object_traits_impl< ::closingPrice, id_mssql >::erase,
    &access::object_traits_impl< ::closingPrice, id_mssql >::erase,
    &access::object_traits_impl< ::closingPrice, id_mssql >::query,
    &access::object_traits_impl< ::closingPrice, id_mssql >::erase_query
  };

  static const object_function_table_entry< ::closingPrice, id_mssql >
  function_table_entry_closingPrice_ (
    &function_table_closingPrice_);
}

#include <odb/post.hxx>
