// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#define ODB_SQLITE_QUERY_COLUMNS_DEF
#include "ClosingPrice-odb-sqlite.hxx"
#undef ODB_SQLITE_QUERY_COLUMNS_DEF

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/schema-catalog-impl.hxx>
#include <odb/function-table.hxx>

#include <odb/sqlite/traits.hxx>
#include <odb/sqlite/database.hxx>
#include <odb/sqlite/transaction.hxx>
#include <odb/sqlite/connection.hxx>
#include <odb/sqlite/statement.hxx>
#include <odb/sqlite/statement-cache.hxx>
#include <odb/sqlite/simple-object-statements.hxx>
#include <odb/sqlite/container-statements.hxx>
#include <odb/sqlite/exceptions.hxx>
#include <odb/sqlite/simple-object-result.hxx>

namespace odb
{
  // id
  //

  bool access::composite_value_traits< ::id, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // Date
    //
    if (t[0UL])
    {
      i.Date_value.capacity (i.Date_size);
      grew = true;
    }

    // Estee_ID
    //
    if (t[1UL])
    {
      i.Estee_ID_value.capacity (i.Estee_ID_size);
      grew = true;
    }

    return grew;
  }

  void access::composite_value_traits< ::id, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (b);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);
    ODB_POTENTIALLY_UNUSED (n);

    // Date
    //
    b[n].type = sqlite::image_traits<
      ::boost::posix_time::ptime,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.Date_value.data ();
    b[n].size = &i.Date_size;
    b[n].capacity = i.Date_value.capacity ();
    b[n].is_null = &i.Date_null;
    n++;

    // Estee_ID
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.Estee_ID_value.data ();
    b[n].size = &i.Estee_ID_size;
    b[n].capacity = i.Estee_ID_value.capacity ();
    b[n].is_null = &i.Estee_ID_null;
    n++;
  }

  bool access::composite_value_traits< ::id, id_sqlite >::
  init (image_type& i,
        const value_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // Date
    //
    {
      ::boost::posix_time::ptime const& v =
        o.Date;

      bool is_null (true);
      std::size_t cap (i.Date_value.capacity ());
      sqlite::value_traits<
          ::boost::posix_time::ptime,
          sqlite::id_text >::set_image (
        i.Date_value,
        i.Date_size,
        is_null,
        v);
      i.Date_null = is_null;
      grew = grew || (cap != i.Date_value.capacity ());
    }

    // Estee_ID
    //
    {
      ::std::string const& v =
        o.Estee_ID;

      bool is_null (false);
      std::size_t cap (i.Estee_ID_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.Estee_ID_value,
        i.Estee_ID_size,
        is_null,
        v);
      i.Estee_ID_null = is_null;
      grew = grew || (cap != i.Estee_ID_value.capacity ());
    }

    return grew;
  }

  void access::composite_value_traits< ::id, id_sqlite >::
  init (value_type& o,
        const image_type&  i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // Date
    //
    {
      ::boost::posix_time::ptime& v =
        o.Date;

      sqlite::value_traits<
          ::boost::posix_time::ptime,
          sqlite::id_text >::set_value (
        v,
        i.Date_value,
        i.Date_size,
        i.Date_null);
    }

    // Estee_ID
    //
    {
      ::std::string& v =
        o.Estee_ID;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.Estee_ID_value,
        i.Estee_ID_size,
        i.Estee_ID_null);
    }
  }

  // closingPrice
  //

  template struct query_columns<
    ::closingPrice,
    id_sqlite,
    access::object_traits_impl< ::closingPrice, id_sqlite > >;

  struct access::object_traits_impl< ::closingPrice, id_sqlite >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      sqlite::connection&,
      image_type&,
      id_image_type&,
      sqlite::binding&,
      sqlite::binding&)
    {
    }
  };

  access::object_traits_impl< ::closingPrice, id_sqlite >::id_type
  access::object_traits_impl< ::closingPrice, id_sqlite >::
  id (const image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      composite_value_traits< ::id, id_sqlite >::init (
        id,
        i._id_value,
        db);
    }

    return id;
  }

  bool access::object_traits_impl< ::closingPrice, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // Open_Interest
    //
    t[0UL] = false;

    // Settlement_price
    //
    t[1UL] = false;

    // Open_Price
    //
    t[2UL] = false;

    // High_Price
    //
    t[3UL] = false;

    // Low_Price
    //
    t[4UL] = false;

    // Close_Price
    //
    t[5UL] = false;

    // Volume
    //
    t[6UL] = false;

    // Net_Traded_Val
    //
    t[7UL] = false;

    // Trades
    //
    t[8UL] = false;

    // Source
    //
    if (t[9UL])
    {
      i.Source_value.capacity (i.Source_size);
      grew = true;
    }

    // _id
    //
    if (composite_value_traits< ::id, id_sqlite >::grow (
          i._id_value, t + 10UL))
      grew = true;

    return grew;
  }

  void access::object_traits_impl< ::closingPrice, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // Open_Interest
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.Open_Interest_value;
    b[n].is_null = &i.Open_Interest_null;
    n++;

    // Settlement_price
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.Settlement_price_value;
    b[n].is_null = &i.Settlement_price_null;
    n++;

    // Open_Price
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.Open_Price_value;
    b[n].is_null = &i.Open_Price_null;
    n++;

    // High_Price
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.High_Price_value;
    b[n].is_null = &i.High_Price_null;
    n++;

    // Low_Price
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.Low_Price_value;
    b[n].is_null = &i.Low_Price_null;
    n++;

    // Close_Price
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.Close_Price_value;
    b[n].is_null = &i.Close_Price_null;
    n++;

    // Volume
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.Volume_value;
    b[n].is_null = &i.Volume_null;
    n++;

    // Net_Traded_Val
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.Net_Traded_Val_value;
    b[n].is_null = &i.Net_Traded_Val_null;
    n++;

    // Trades
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.Trades_value;
    b[n].is_null = &i.Trades_null;
    n++;

    // Source
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.Source_value.data ();
    b[n].size = &i.Source_size;
    b[n].capacity = i.Source_value.capacity ();
    b[n].is_null = &i.Source_null;
    n++;

    // _id
    //
    if (sk != statement_update)
    {
      composite_value_traits< ::id, id_sqlite >::bind (
        b + n, i._id_value, sk);
      n += 2UL;
    }
  }

  void access::object_traits_impl< ::closingPrice, id_sqlite >::
  bind (sqlite::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    sqlite::statement_kind sk (sqlite::statement_select);
    composite_value_traits< ::id, id_sqlite >::bind (
      b + n, i.id_value, sk);
  }

  bool access::object_traits_impl< ::closingPrice, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // Open_Interest
    //
    {
      double const& v =
        o.Open_Interest;

      bool is_null (true);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.Open_Interest_value,
        is_null,
        v);
      i.Open_Interest_null = is_null;
    }

    // Settlement_price
    //
    {
      double const& v =
        o.Settlement_price;

      bool is_null (true);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.Settlement_price_value,
        is_null,
        v);
      i.Settlement_price_null = is_null;
    }

    // Open_Price
    //
    {
      double const& v =
        o.Open_Price;

      bool is_null (true);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.Open_Price_value,
        is_null,
        v);
      i.Open_Price_null = is_null;
    }

    // High_Price
    //
    {
      double const& v =
        o.High_Price;

      bool is_null (true);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.High_Price_value,
        is_null,
        v);
      i.High_Price_null = is_null;
    }

    // Low_Price
    //
    {
      double const& v =
        o.Low_Price;

      bool is_null (true);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.Low_Price_value,
        is_null,
        v);
      i.Low_Price_null = is_null;
    }

    // Close_Price
    //
    {
      double const& v =
        o.Close_Price;

      bool is_null (true);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.Close_Price_value,
        is_null,
        v);
      i.Close_Price_null = is_null;
    }

    // Volume
    //
    {
      double const& v =
        o.Volume;

      bool is_null (true);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.Volume_value,
        is_null,
        v);
      i.Volume_null = is_null;
    }

    // Net_Traded_Val
    //
    {
      double const& v =
        o.Net_Traded_Val;

      bool is_null (true);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.Net_Traded_Val_value,
        is_null,
        v);
      i.Net_Traded_Val_null = is_null;
    }

    // Trades
    //
    {
      int const& v =
        o.Trades;

      bool is_null (false);
      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_image (
        i.Trades_value,
        is_null,
        v);
      i.Trades_null = is_null;
    }

    // Source
    //
    {
      ::std::string const& v =
        o.Source;

      bool is_null (false);
      std::size_t cap (i.Source_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.Source_value,
        i.Source_size,
        is_null,
        v);
      i.Source_null = is_null;
      grew = grew || (cap != i.Source_value.capacity ());
    }

    // _id
    //
    if (sk == statement_insert)
    {
      ::id const& v =
        o._id;

      if (composite_value_traits< ::id, id_sqlite >::init (
            i._id_value,
            v,
            sk))
        grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::closingPrice, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // Open_Interest
    //
    {
      double& v =
        o.Open_Interest;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.Open_Interest_value,
        i.Open_Interest_null);
    }

    // Settlement_price
    //
    {
      double& v =
        o.Settlement_price;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.Settlement_price_value,
        i.Settlement_price_null);
    }

    // Open_Price
    //
    {
      double& v =
        o.Open_Price;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.Open_Price_value,
        i.Open_Price_null);
    }

    // High_Price
    //
    {
      double& v =
        o.High_Price;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.High_Price_value,
        i.High_Price_null);
    }

    // Low_Price
    //
    {
      double& v =
        o.Low_Price;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.Low_Price_value,
        i.Low_Price_null);
    }

    // Close_Price
    //
    {
      double& v =
        o.Close_Price;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.Close_Price_value,
        i.Close_Price_null);
    }

    // Volume
    //
    {
      double& v =
        o.Volume;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.Volume_value,
        i.Volume_null);
    }

    // Net_Traded_Val
    //
    {
      double& v =
        o.Net_Traded_Val;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.Net_Traded_Val_value,
        i.Net_Traded_Val_null);
    }

    // Trades
    //
    {
      int& v =
        o.Trades;

      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_value (
        v,
        i.Trades_value,
        i.Trades_null);
    }

    // Source
    //
    {
      ::std::string& v =
        o.Source;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.Source_value,
        i.Source_size,
        i.Source_null);
    }

    // _id
    //
    {
      ::id& v =
        o._id;

      composite_value_traits< ::id, id_sqlite >::init (
        v,
        i._id_value,
        db);
    }
  }

  void access::object_traits_impl< ::closingPrice, id_sqlite >::
  init (id_image_type& i, const id_type& id)
  {
    bool grew (false);
    sqlite::statement_kind sk (sqlite::statement_select);
    {
      if (composite_value_traits< ::id, id_sqlite >::init (
            i.id_value,
            id,
            sk))
        grew = true;
    }

    if (grew)
      i.version++;
  }

  const char access::object_traits_impl< ::closingPrice, id_sqlite >::persist_statement[] =
  "INSERT INTO \"closingPrice\" "
  "(\"Open_Interest\", "
  "\"Settlement_price\", "
  "\"Open_Price\", "
  "\"High_Price\", "
  "\"Low_Price\", "
  "\"Close_Price\", "
  "\"Volume\", "
  "\"Net_Traded_Val\", "
  "\"Trades\", "
  "\"Source\", "
  "\"Date\", "
  "\"Estee_ID\") "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::closingPrice, id_sqlite >::find_statement[] =
  "SELECT "
  "\"closingPrice\".\"Open_Interest\", "
  "\"closingPrice\".\"Settlement_price\", "
  "\"closingPrice\".\"Open_Price\", "
  "\"closingPrice\".\"High_Price\", "
  "\"closingPrice\".\"Low_Price\", "
  "\"closingPrice\".\"Close_Price\", "
  "\"closingPrice\".\"Volume\", "
  "\"closingPrice\".\"Net_Traded_Val\", "
  "\"closingPrice\".\"Trades\", "
  "\"closingPrice\".\"Source\", "
  "\"closingPrice\".\"Date\", "
  "\"closingPrice\".\"Estee_ID\" "
  "FROM \"closingPrice\" "
  "WHERE \"closingPrice\".\"Date\"=? AND \"closingPrice\".\"Estee_ID\"=?";

  const char access::object_traits_impl< ::closingPrice, id_sqlite >::update_statement[] =
  "UPDATE \"closingPrice\" "
  "SET "
  "\"Open_Interest\"=?, "
  "\"Settlement_price\"=?, "
  "\"Open_Price\"=?, "
  "\"High_Price\"=?, "
  "\"Low_Price\"=?, "
  "\"Close_Price\"=?, "
  "\"Volume\"=?, "
  "\"Net_Traded_Val\"=?, "
  "\"Trades\"=?, "
  "\"Source\"=? "
  "WHERE \"Date\"=? AND \"Estee_ID\"=?";

  const char access::object_traits_impl< ::closingPrice, id_sqlite >::erase_statement[] =
  "DELETE FROM \"closingPrice\" "
  "WHERE \"Date\"=? AND \"Estee_ID\"=?";

  const char access::object_traits_impl< ::closingPrice, id_sqlite >::query_statement[] =
  "SELECT "
  "\"closingPrice\".\"Open_Interest\", "
  "\"closingPrice\".\"Settlement_price\", "
  "\"closingPrice\".\"Open_Price\", "
  "\"closingPrice\".\"High_Price\", "
  "\"closingPrice\".\"Low_Price\", "
  "\"closingPrice\".\"Close_Price\", "
  "\"closingPrice\".\"Volume\", "
  "\"closingPrice\".\"Net_Traded_Val\", "
  "\"closingPrice\".\"Trades\", "
  "\"closingPrice\".\"Source\", "
  "\"closingPrice\".\"Date\", "
  "\"closingPrice\".\"Estee_ID\" "
  "FROM \"closingPrice\"";

  const char access::object_traits_impl< ::closingPrice, id_sqlite >::erase_query_statement[] =
  "DELETE FROM \"closingPrice\"";

  const char access::object_traits_impl< ::closingPrice, id_sqlite >::table_name[] =
  "\"closingPrice\"";

  void access::object_traits_impl< ::closingPrice, id_sqlite >::
  persist (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::closingPrice, id_sqlite >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;
    using sqlite::update_statement;

    callback (db, obj, callback_event::pre_update);

    sqlite::transaction& tr (sqlite::transaction::current ());
    sqlite::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj._id);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::closingPrice, id_sqlite >::
  erase (database& db, const id_type& id)
  {
    using namespace sqlite;

    ODB_POTENTIALLY_UNUSED (db);

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::closingPrice, id_sqlite >::pointer_type
  access::object_traits_impl< ::closingPrice, id_sqlite >::
  find (database& db, const id_type& id)
  {
    using namespace sqlite;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::closingPrice, id_sqlite >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::closingPrice, id_sqlite >::
  reload (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj._id);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::closingPrice, id_sqlite >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace sqlite;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::closingPrice, id_sqlite >::object_type >
  access::object_traits_impl< ::closingPrice, id_sqlite >::
  query (database&, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) sqlite::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  result< access::object_traits_impl< ::closingPrice, id_sqlite >::object_type >
  access::object_traits_impl< ::closingPrice, id_sqlite >::
  query (database& db, const odb::query_base& q)
  {
    return query (db, query_base_type (q));
  }

  unsigned long long access::object_traits_impl< ::closingPrice, id_sqlite >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }

  unsigned long long access::object_traits_impl< ::closingPrice, id_sqlite >::
  erase_query (database& db, const odb::query_base& q)
  {
    return erase_query (db, query_base_type (q));
  }

  static const
  access::object_traits_impl< ::closingPrice, id_common >::
  function_table_type function_table_closingPrice_ =
  {
    &access::object_traits_impl< ::closingPrice, id_sqlite >::persist,
    &access::object_traits_impl< ::closingPrice, id_sqlite >::find,
    &access::object_traits_impl< ::closingPrice, id_sqlite >::find,
    &access::object_traits_impl< ::closingPrice, id_sqlite >::reload,
    &access::object_traits_impl< ::closingPrice, id_sqlite >::update,
    &access::object_traits_impl< ::closingPrice, id_sqlite >::erase,
    &access::object_traits_impl< ::closingPrice, id_sqlite >::erase,
    &access::object_traits_impl< ::closingPrice, id_sqlite >::query,
    &access::object_traits_impl< ::closingPrice, id_sqlite >::erase_query
  };

  static const object_function_table_entry< ::closingPrice, id_sqlite >
  function_table_entry_closingPrice_ (
    &function_table_closingPrice_);
}

namespace odb
{
  static bool
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);
    ODB_POTENTIALLY_UNUSED (drop);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          return true;
        }
        case 2:
        {
          db.execute ("DROP TABLE IF EXISTS \"closingPrice\"");
          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE \"closingPrice\" (\n"
                      "  \"Open_Interest\" REAL NULL,\n"
                      "  \"Settlement_price\" REAL NULL,\n"
                      "  \"Open_Price\" REAL NULL,\n"
                      "  \"High_Price\" REAL NULL,\n"
                      "  \"Low_Price\" REAL NULL,\n"
                      "  \"Close_Price\" REAL NULL,\n"
                      "  \"Volume\" REAL NULL,\n"
                      "  \"Net_Traded_Val\" REAL NULL,\n"
                      "  \"Trades\" INTEGER NOT NULL,\n"
                      "  \"Source\" TEXT NOT NULL,\n"
                      "  \"Date\" DATETIME NOT NULL,\n"
                      "  \"Estee_ID\" TEXT NOT NULL,\n"
                      "  PRIMARY KEY (\"Date\",\n"
                      "               \"Estee_ID\"))");
          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_create_entry
  create_schema_entry_ (
    id_sqlite,
    "",
    &create_schema);
}

#include <odb/post.hxx>
