/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

IF OBJECT_ID('person', 'U') IS NOT NULL
  DROP TABLE [person];
GO

CREATE TABLE [person] (
  [id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
  [first] VARCHAR(512) NOT NULL,
  [last] VARCHAR(512) NOT NULL,
  [age] SMALLINT NOT NULL);
GO

