/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

IF OBJECT_ID('inh_reuse_contractor', 'U') IS NOT NULL
  DROP TABLE [inh_reuse_contractor];
GO

IF OBJECT_ID('inh_reuse_temporary_employee', 'U') IS NOT NULL
  DROP TABLE [inh_reuse_temporary_employee];
GO

IF OBJECT_ID('inh_reuse_permanent_employee', 'U') IS NOT NULL
  DROP TABLE [inh_reuse_permanent_employee];
GO

CREATE TABLE [inh_reuse_permanent_employee] (
  [first] VARCHAR(512) NOT NULL,
  [last] VARCHAR(512) NOT NULL,
  [id] BIGINT NOT NULL PRIMARY KEY IDENTITY);
GO

CREATE TABLE [inh_reuse_temporary_employee] (
  [first] VARCHAR(512) NOT NULL,
  [last] VARCHAR(512) NOT NULL,
  [id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
  [duration] BIGINT NOT NULL);
GO

CREATE TABLE [inh_reuse_contractor] (
  [first] VARCHAR(512) NOT NULL,
  [last] VARCHAR(512) NOT NULL,
  [email] VARCHAR(256) NOT NULL PRIMARY KEY);
GO

