/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

IF OBJECT_ID('c_person_name_extras_aliases', 'U') IS NOT NULL
  DROP TABLE [c_person_name_extras_aliases];
GO

IF OBJECT_ID('c_person', 'U') IS NOT NULL
  DROP TABLE [c_person];
GO

CREATE TABLE [c_person] (
  [email_recipient] VARCHAR(256) NOT NULL,
  [email_domain] VARCHAR(256) NOT NULL,
  [name_first] VARCHAR(512) NOT NULL,
  [name_last] VARCHAR(512) NOT NULL,
  [name_title] VARCHAR(512) NOT NULL,
  [name_extras_nickname] VARCHAR(512) NOT NULL,
  [phone_first] VARCHAR(512) NOT NULL,
  [phone_second] VARCHAR(512) NOT NULL,
  PRIMARY KEY ([email_recipient],
               [email_domain]));
GO

CREATE TABLE [c_person_name_extras_aliases] (
  [object_id_recipient] VARCHAR(256) NOT NULL,
  [object_id_domain] VARCHAR(256) NOT NULL,
  [index] BIGINT NOT NULL,
  [value_first] VARCHAR(512) NOT NULL,
  [value_last] VARCHAR(512) NOT NULL,
  CONSTRAINT [c_person_name_extras_aliases_object_id_fk]
    FOREIGN KEY ([object_id_recipient],
                 [object_id_domain])
    REFERENCES [c_person] ([email_recipient],
                           [email_domain])
    ON DELETE CASCADE);
GO

CREATE INDEX [object_id_i]
  ON [c_person_name_extras_aliases] (
    [object_id_recipient],
    [object_id_domain]);
GO

CREATE INDEX [index_i]
  ON [c_person_name_extras_aliases] ([index]);
GO

