/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

IF OBJECT_ID('optimistic_person', 'U') IS NOT NULL
  DROP TABLE [optimistic_person];
GO

CREATE TABLE [optimistic_person] (
  [id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
  [version] BIGINT NOT NULL,
  [first] VARCHAR(512) NOT NULL,
  [last] VARCHAR(512) NOT NULL,
  [age] SMALLINT NOT NULL);
GO

