/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

IF OBJECT_ID('container_person_age_weight', 'U') IS NOT NULL
  DROP TABLE [container_person_age_weight];
GO

IF OBJECT_ID('container_person_emails', 'U') IS NOT NULL
  DROP TABLE [container_person_emails];
GO

IF OBJECT_ID('container_person_nicknames', 'U') IS NOT NULL
  DROP TABLE [container_person_nicknames];
GO

IF OBJECT_ID('container_person', 'U') IS NOT NULL
  DROP TABLE [container_person];
GO

CREATE TABLE [container_person] (
  [id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
  [first] VARCHAR(512) NOT NULL,
  [last] VARCHAR(512) NOT NULL);
GO

CREATE TABLE [container_person_nicknames] (
  [object_id] BIGINT NOT NULL,
  [index] BIGINT NOT NULL,
  [value] VARCHAR(512) NOT NULL,
  CONSTRAINT [container_person_nicknames_object_id_fk]
    FOREIGN KEY ([object_id])
    REFERENCES [container_person] ([id])
    ON DELETE CASCADE);
GO

CREATE INDEX [object_id_i]
  ON [container_person_nicknames] ([object_id]);
GO

CREATE INDEX [index_i]
  ON [container_person_nicknames] ([index]);
GO

CREATE TABLE [container_person_emails] (
  [object_id] BIGINT NOT NULL,
  [value] VARCHAR(512) NOT NULL,
  CONSTRAINT [container_person_emails_object_id_fk]
    FOREIGN KEY ([object_id])
    REFERENCES [container_person] ([id])
    ON DELETE CASCADE);
GO

CREATE INDEX [object_id_i]
  ON [container_person_emails] ([object_id]);
GO

CREATE TABLE [container_person_age_weight] (
  [object_id] BIGINT NOT NULL,
  [key] SMALLINT NOT NULL,
  [value] REAL NOT NULL,
  CONSTRAINT [container_person_age_weight_object_id_fk]
    FOREIGN KEY ([object_id])
    REFERENCES [container_person] ([id])
    ON DELETE CASCADE);
GO

CREATE INDEX [object_id_i]
  ON [container_person_age_weight] ([object_id]);
GO

