/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

IF OBJECT_ID('pimpl_person', 'U') IS NOT NULL
  DROP TABLE [pimpl_person];
GO

CREATE TABLE [pimpl_person] (
  [email] VARCHAR(256) NOT NULL PRIMARY KEY,
  [name] VARCHAR(512) NOT NULL,
  [age] SMALLINT NOT NULL);
GO

