// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef ESTEE_MASTER_ODB_MYSQL_HXX
#define ESTEE_MASTER_ODB_MYSQL_HXX

// Begin prologue.
//
#include <odb/boost/version.hxx>
#if ODB_BOOST_VERSION != 2040000 // 2.4.0
#  error ODB and C++ compilers see different libodb-boost interface versions
#endif
#include <boost/shared_ptr.hpp>
#include <odb/boost/smart-ptr/pointer-traits.hxx>
#include <odb/boost/smart-ptr/wrapper-traits.hxx>
#include <odb/boost/optional/wrapper-traits.hxx>
#include <odb/boost/unordered/container-traits.hxx>
#include <odb/boost/date-time/mysql/gregorian-traits.hxx>
#include <odb/boost/date-time/mysql/posix-time-traits.hxx>
#include <odb/boost/multi-index/container-traits.hxx>
#include <odb/boost/uuid/mysql/uuid-traits.hxx>
//
// End prologue.

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "EsteeMaster.h"

#include "EsteeMaster-odb.hxx"

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>
#include <odb/mysql/query-dynamic.hxx>

namespace odb
{
  // EsteeMaster
  //
  template <typename A>
  struct query_columns< ::EsteeMaster, id_mysql, A >
  {
    // DataFeed_Ticker
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    DataFeed_Ticker_type_;

    static const DataFeed_Ticker_type_ DataFeed_Ticker;

    // Underlying_Ticker
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    Underlying_Ticker_type_;

    static const Underlying_Ticker_type_ Underlying_Ticker;

    // ISIN
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    ISIN_type_;

    static const ISIN_type_ ISIN;

    // Exchange_Code
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    Exchange_Code_type_;

    static const Exchange_Code_type_ Exchange_Code;

    // Option_Type
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    Option_Type_type_;

    static const Option_Type_type_ Option_Type;

    // Status
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    Status_type_;

    static const Status_type_ Status;

    // TOKEN2
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    TOKEN2_type_;

    static const TOKEN2_type_ TOKEN2;

    // Expiry_Date2
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    Expiry_Date2_type_;

    static const Expiry_Date2_type_ Expiry_Date2;

    // SERIES
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    SERIES_type_;

    static const SERIES_type_ SERIES;

    // Source
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    Source_type_;

    static const Source_type_ Source;

    // UnderlyingEstee_Id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    UnderlyingEstee_Id_type_;

    static const UnderlyingEstee_Id_type_ UnderlyingEstee_Id;

    // Strike_Price
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        double,
        mysql::id_double >::query_type,
      mysql::id_double >
    Strike_Price_type_;

    static const Strike_Price_type_ Strike_Price;

    // Tick_Size
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        double,
        mysql::id_double >::query_type,
      mysql::id_double >
    Tick_Size_type_;

    static const Tick_Size_type_ Tick_Size;

    // Lot_Size
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        int,
        mysql::id_long >::query_type,
      mysql::id_long >
    Lot_Size_type_;

    static const Lot_Size_type_ Lot_Size;

    // Security_Type
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        int,
        mysql::id_long >::query_type,
      mysql::id_long >
    Security_Type_type_;

    static const Security_Type_type_ Security_Type;

    // Token
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        int,
        mysql::id_long >::query_type,
      mysql::id_long >
    Token_type_;

    static const Token_type_ Token;

    // Quote_Size
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        int,
        mysql::id_long >::query_type,
      mysql::id_long >
    Quote_Size_type_;

    static const Quote_Size_type_ Quote_Size;

    // Instrument_Type
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        int,
        mysql::id_long >::query_type,
      mysql::id_long >
    Instrument_Type_type_;

    static const Instrument_Type_type_ Instrument_Type;

    // TradingCurrency
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        int,
        mysql::id_long >::query_type,
      mysql::id_long >
    TradingCurrency_type_;

    static const TradingCurrency_type_ TradingCurrency;

    // SettlementCurrency
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        int,
        mysql::id_long >::query_type,
      mysql::id_long >
    SettlementCurrency_type_;

    static const SettlementCurrency_type_ SettlementCurrency;

    // TickSizeSlabId
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        int,
        mysql::id_long >::query_type,
      mysql::id_long >
    TickSizeSlabId_type_;

    static const TickSizeSlabId_type_ TickSizeSlabId;

    // AsOfDate
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::boost::posix_time::ptime,
        mysql::id_datetime >::query_type,
      mysql::id_datetime >
    AsOfDate_type_;

    static const AsOfDate_type_ AsOfDate;

    // Last_update_time
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::boost::posix_time::ptime,
        mysql::id_datetime >::query_type,
      mysql::id_datetime >
    Last_update_time_type_;

    static const Last_update_time_type_ Last_update_time;

    // Expiry_Date
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::boost::posix_time::ptime,
        mysql::id_datetime >::query_type,
      mysql::id_datetime >
    Expiry_Date_type_;

    static const Expiry_Date_type_ Expiry_Date;

    // SettlementDate
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::boost::posix_time::ptime,
        mysql::id_datetime >::query_type,
      mysql::id_datetime >
    SettlementDate_type_;

    static const SettlementDate_type_ SettlementDate;

    // TradingStartDate
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::boost::posix_time::ptime,
        mysql::id_datetime >::query_type,
      mysql::id_datetime >
    TradingStartDate_type_;

    static const TradingStartDate_type_ TradingStartDate;

    // LastTradingDate
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::boost::posix_time::ptime,
        mysql::id_datetime >::query_type,
      mysql::id_datetime >
    LastTradingDate_type_;

    static const LastTradingDate_type_ LastTradingDate;

    // Estee_ID
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    Estee_ID_type_;

    static const Estee_ID_type_ Estee_ID;
  };

#ifdef ODB_MYSQL_QUERY_COLUMNS_DEF

  template <typename A>
  const typename query_columns< ::EsteeMaster, id_mysql, A >::DataFeed_Ticker_type_
  query_columns< ::EsteeMaster, id_mysql, A >::
  DataFeed_Ticker (query_columns< ::EsteeMaster, id_common, typename A::common_traits >::DataFeed_Ticker,
                   A::table_name, "`DataFeed_Ticker`", 0);

  template <typename A>
  const typename query_columns< ::EsteeMaster, id_mysql, A >::Underlying_Ticker_type_
  query_columns< ::EsteeMaster, id_mysql, A >::
  Underlying_Ticker (query_columns< ::EsteeMaster, id_common, typename A::common_traits >::Underlying_Ticker,
                     A::table_name, "`Underlying_Ticker`", 0);

  template <typename A>
  const typename query_columns< ::EsteeMaster, id_mysql, A >::ISIN_type_
  query_columns< ::EsteeMaster, id_mysql, A >::
  ISIN (query_columns< ::EsteeMaster, id_common, typename A::common_traits >::ISIN,
        A::table_name, "`ISIN`", 0);

  template <typename A>
  const typename query_columns< ::EsteeMaster, id_mysql, A >::Exchange_Code_type_
  query_columns< ::EsteeMaster, id_mysql, A >::
  Exchange_Code (query_columns< ::EsteeMaster, id_common, typename A::common_traits >::Exchange_Code,
                 A::table_name, "`Exchange_Code`", 0);

  template <typename A>
  const typename query_columns< ::EsteeMaster, id_mysql, A >::Option_Type_type_
  query_columns< ::EsteeMaster, id_mysql, A >::
  Option_Type (query_columns< ::EsteeMaster, id_common, typename A::common_traits >::Option_Type,
               A::table_name, "`Option_Type`", 0);

  template <typename A>
  const typename query_columns< ::EsteeMaster, id_mysql, A >::Status_type_
  query_columns< ::EsteeMaster, id_mysql, A >::
  Status (query_columns< ::EsteeMaster, id_common, typename A::common_traits >::Status,
          A::table_name, "`Status`", 0);

  template <typename A>
  const typename query_columns< ::EsteeMaster, id_mysql, A >::TOKEN2_type_
  query_columns< ::EsteeMaster, id_mysql, A >::
  TOKEN2 (query_columns< ::EsteeMaster, id_common, typename A::common_traits >::TOKEN2,
          A::table_name, "`TOKEN2`", 0);

  template <typename A>
  const typename query_columns< ::EsteeMaster, id_mysql, A >::Expiry_Date2_type_
  query_columns< ::EsteeMaster, id_mysql, A >::
  Expiry_Date2 (query_columns< ::EsteeMaster, id_common, typename A::common_traits >::Expiry_Date2,
                A::table_name, "`Expiry_Date2`", 0);

  template <typename A>
  const typename query_columns< ::EsteeMaster, id_mysql, A >::SERIES_type_
  query_columns< ::EsteeMaster, id_mysql, A >::
  SERIES (query_columns< ::EsteeMaster, id_common, typename A::common_traits >::SERIES,
          A::table_name, "`SERIES`", 0);

  template <typename A>
  const typename query_columns< ::EsteeMaster, id_mysql, A >::Source_type_
  query_columns< ::EsteeMaster, id_mysql, A >::
  Source (query_columns< ::EsteeMaster, id_common, typename A::common_traits >::Source,
          A::table_name, "`Source`", 0);

  template <typename A>
  const typename query_columns< ::EsteeMaster, id_mysql, A >::UnderlyingEstee_Id_type_
  query_columns< ::EsteeMaster, id_mysql, A >::
  UnderlyingEstee_Id (query_columns< ::EsteeMaster, id_common, typename A::common_traits >::UnderlyingEstee_Id,
                      A::table_name, "`UnderlyingEstee_Id`", 0);

  template <typename A>
  const typename query_columns< ::EsteeMaster, id_mysql, A >::Strike_Price_type_
  query_columns< ::EsteeMaster, id_mysql, A >::
  Strike_Price (query_columns< ::EsteeMaster, id_common, typename A::common_traits >::Strike_Price,
                A::table_name, "`Strike_Price`", 0);

  template <typename A>
  const typename query_columns< ::EsteeMaster, id_mysql, A >::Tick_Size_type_
  query_columns< ::EsteeMaster, id_mysql, A >::
  Tick_Size (query_columns< ::EsteeMaster, id_common, typename A::common_traits >::Tick_Size,
             A::table_name, "`Tick_Size`", 0);

  template <typename A>
  const typename query_columns< ::EsteeMaster, id_mysql, A >::Lot_Size_type_
  query_columns< ::EsteeMaster, id_mysql, A >::
  Lot_Size (query_columns< ::EsteeMaster, id_common, typename A::common_traits >::Lot_Size,
            A::table_name, "`Lot_Size`", 0);

  template <typename A>
  const typename query_columns< ::EsteeMaster, id_mysql, A >::Security_Type_type_
  query_columns< ::EsteeMaster, id_mysql, A >::
  Security_Type (query_columns< ::EsteeMaster, id_common, typename A::common_traits >::Security_Type,
                 A::table_name, "`Security_Type`", 0);

  template <typename A>
  const typename query_columns< ::EsteeMaster, id_mysql, A >::Token_type_
  query_columns< ::EsteeMaster, id_mysql, A >::
  Token (query_columns< ::EsteeMaster, id_common, typename A::common_traits >::Token,
         A::table_name, "`Token`", 0);

  template <typename A>
  const typename query_columns< ::EsteeMaster, id_mysql, A >::Quote_Size_type_
  query_columns< ::EsteeMaster, id_mysql, A >::
  Quote_Size (query_columns< ::EsteeMaster, id_common, typename A::common_traits >::Quote_Size,
              A::table_name, "`Quote_Size`", 0);

  template <typename A>
  const typename query_columns< ::EsteeMaster, id_mysql, A >::Instrument_Type_type_
  query_columns< ::EsteeMaster, id_mysql, A >::
  Instrument_Type (query_columns< ::EsteeMaster, id_common, typename A::common_traits >::Instrument_Type,
                   A::table_name, "`Instrument_Type`", 0);

  template <typename A>
  const typename query_columns< ::EsteeMaster, id_mysql, A >::TradingCurrency_type_
  query_columns< ::EsteeMaster, id_mysql, A >::
  TradingCurrency (query_columns< ::EsteeMaster, id_common, typename A::common_traits >::TradingCurrency,
                   A::table_name, "`TradingCurrency`", 0);

  template <typename A>
  const typename query_columns< ::EsteeMaster, id_mysql, A >::SettlementCurrency_type_
  query_columns< ::EsteeMaster, id_mysql, A >::
  SettlementCurrency (query_columns< ::EsteeMaster, id_common, typename A::common_traits >::SettlementCurrency,
                      A::table_name, "`SettlementCurrency`", 0);

  template <typename A>
  const typename query_columns< ::EsteeMaster, id_mysql, A >::TickSizeSlabId_type_
  query_columns< ::EsteeMaster, id_mysql, A >::
  TickSizeSlabId (query_columns< ::EsteeMaster, id_common, typename A::common_traits >::TickSizeSlabId,
                  A::table_name, "`TickSizeSlabId`", 0);

  template <typename A>
  const typename query_columns< ::EsteeMaster, id_mysql, A >::AsOfDate_type_
  query_columns< ::EsteeMaster, id_mysql, A >::
  AsOfDate (query_columns< ::EsteeMaster, id_common, typename A::common_traits >::AsOfDate,
            A::table_name, "`AsOfDate`", 0);

  template <typename A>
  const typename query_columns< ::EsteeMaster, id_mysql, A >::Last_update_time_type_
  query_columns< ::EsteeMaster, id_mysql, A >::
  Last_update_time (query_columns< ::EsteeMaster, id_common, typename A::common_traits >::Last_update_time,
                    A::table_name, "`Last_update_time`", 0);

  template <typename A>
  const typename query_columns< ::EsteeMaster, id_mysql, A >::Expiry_Date_type_
  query_columns< ::EsteeMaster, id_mysql, A >::
  Expiry_Date (query_columns< ::EsteeMaster, id_common, typename A::common_traits >::Expiry_Date,
               A::table_name, "`Expiry_Date`", 0);

  template <typename A>
  const typename query_columns< ::EsteeMaster, id_mysql, A >::SettlementDate_type_
  query_columns< ::EsteeMaster, id_mysql, A >::
  SettlementDate (query_columns< ::EsteeMaster, id_common, typename A::common_traits >::SettlementDate,
                  A::table_name, "`SettlementDate`", 0);

  template <typename A>
  const typename query_columns< ::EsteeMaster, id_mysql, A >::TradingStartDate_type_
  query_columns< ::EsteeMaster, id_mysql, A >::
  TradingStartDate (query_columns< ::EsteeMaster, id_common, typename A::common_traits >::TradingStartDate,
                    A::table_name, "`TradingStartDate`", 0);

  template <typename A>
  const typename query_columns< ::EsteeMaster, id_mysql, A >::LastTradingDate_type_
  query_columns< ::EsteeMaster, id_mysql, A >::
  LastTradingDate (query_columns< ::EsteeMaster, id_common, typename A::common_traits >::LastTradingDate,
                   A::table_name, "`LastTradingDate`", 0);

  template <typename A>
  const typename query_columns< ::EsteeMaster, id_mysql, A >::Estee_ID_type_
  query_columns< ::EsteeMaster, id_mysql, A >::
  Estee_ID (query_columns< ::EsteeMaster, id_common, typename A::common_traits >::Estee_ID,
            A::table_name, "`Estee_ID`", 0);

#endif // ODB_MYSQL_QUERY_COLUMNS_DEF

  template <typename A>
  struct pointer_query_columns< ::EsteeMaster, id_mysql, A >:
    query_columns< ::EsteeMaster, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::EsteeMaster, id_mysql >:
    public access::object_traits< ::EsteeMaster >
  {
    public:
    typedef access::object_traits_impl< ::EsteeMaster, id_common > common_traits;

    struct id_image_type
    {
      details::buffer id_value;
      unsigned long id_size;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // DataFeed_Ticker
      //
      details::buffer DataFeed_Ticker_value;
      unsigned long DataFeed_Ticker_size;
      my_bool DataFeed_Ticker_null;

      // Underlying_Ticker
      //
      details::buffer Underlying_Ticker_value;
      unsigned long Underlying_Ticker_size;
      my_bool Underlying_Ticker_null;

      // ISIN
      //
      details::buffer ISIN_value;
      unsigned long ISIN_size;
      my_bool ISIN_null;

      // Exchange_Code
      //
      details::buffer Exchange_Code_value;
      unsigned long Exchange_Code_size;
      my_bool Exchange_Code_null;

      // Option_Type
      //
      details::buffer Option_Type_value;
      unsigned long Option_Type_size;
      my_bool Option_Type_null;

      // Status
      //
      details::buffer Status_value;
      unsigned long Status_size;
      my_bool Status_null;

      // TOKEN2
      //
      details::buffer TOKEN2_value;
      unsigned long TOKEN2_size;
      my_bool TOKEN2_null;

      // Expiry_Date2
      //
      details::buffer Expiry_Date2_value;
      unsigned long Expiry_Date2_size;
      my_bool Expiry_Date2_null;

      // SERIES
      //
      details::buffer SERIES_value;
      unsigned long SERIES_size;
      my_bool SERIES_null;

      // Source
      //
      details::buffer Source_value;
      unsigned long Source_size;
      my_bool Source_null;

      // UnderlyingEstee_Id
      //
      details::buffer UnderlyingEstee_Id_value;
      unsigned long UnderlyingEstee_Id_size;
      my_bool UnderlyingEstee_Id_null;

      // Strike_Price
      //
      double Strike_Price_value;
      my_bool Strike_Price_null;

      // Tick_Size
      //
      double Tick_Size_value;
      my_bool Tick_Size_null;

      // Lot_Size
      //
      int Lot_Size_value;
      my_bool Lot_Size_null;

      // Security_Type
      //
      int Security_Type_value;
      my_bool Security_Type_null;

      // Token
      //
      int Token_value;
      my_bool Token_null;

      // Quote_Size
      //
      int Quote_Size_value;
      my_bool Quote_Size_null;

      // Instrument_Type
      //
      int Instrument_Type_value;
      my_bool Instrument_Type_null;

      // TradingCurrency
      //
      int TradingCurrency_value;
      my_bool TradingCurrency_null;

      // SettlementCurrency
      //
      int SettlementCurrency_value;
      my_bool SettlementCurrency_null;

      // TickSizeSlabId
      //
      int TickSizeSlabId_value;
      my_bool TickSizeSlabId_null;

      // AsOfDate
      //
      MYSQL_TIME AsOfDate_value;
      my_bool AsOfDate_null;

      // Last_update_time
      //
      MYSQL_TIME Last_update_time_value;
      my_bool Last_update_time_null;

      // Expiry_Date
      //
      MYSQL_TIME Expiry_Date_value;
      my_bool Expiry_Date_null;

      // SettlementDate
      //
      MYSQL_TIME SettlementDate_value;
      my_bool SettlementDate_null;

      // TradingStartDate
      //
      MYSQL_TIME TradingStartDate_value;
      my_bool TradingStartDate_null;

      // LastTradingDate
      //
      MYSQL_TIME LastTradingDate_value;
      my_bool LastTradingDate_null;

      // Estee_ID
      //
      details::buffer Estee_ID_value;
      unsigned long Estee_ID_size;
      my_bool Estee_ID_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 28UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static result<object_type>
    query (database&, const odb::query_base&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const odb::query_base&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  // EsteeMaster
  //
}

#include "EsteeMaster-odb-mysql.ixx"

#include <odb/post.hxx>

#endif // ESTEE_MASTER_ODB_MYSQL_HXX
