/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

IF OBJECT_ID('access_person', 'U') IS NOT NULL
  DROP TABLE [access_person];
GO

CREATE TABLE [access_person] (
  [email] VARCHAR(256) NOT NULL PRIMARY KEY,
  [first] VARCHAR(512) NOT NULL,
  [middle] VARCHAR(512) NOT NULL,
  [last] VARCHAR(512) NOT NULL,
  [age] SMALLINT NOT NULL);
GO

