// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#define ODB_SQLITE_QUERY_COLUMNS_DEF
#include "EsteeMaster-odb-sqlite.hxx"
#undef ODB_SQLITE_QUERY_COLUMNS_DEF

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/schema-catalog-impl.hxx>
#include <odb/function-table.hxx>

#include <odb/sqlite/traits.hxx>
#include <odb/sqlite/database.hxx>
#include <odb/sqlite/transaction.hxx>
#include <odb/sqlite/connection.hxx>
#include <odb/sqlite/statement.hxx>
#include <odb/sqlite/statement-cache.hxx>
#include <odb/sqlite/simple-object-statements.hxx>
#include <odb/sqlite/container-statements.hxx>
#include <odb/sqlite/exceptions.hxx>
#include <odb/sqlite/simple-object-result.hxx>

namespace odb
{
  // EsteeMaster
  //

  template struct query_columns<
    ::EsteeMaster,
    id_sqlite,
    access::object_traits_impl< ::EsteeMaster, id_sqlite > >;

  struct access::object_traits_impl< ::EsteeMaster, id_sqlite >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      sqlite::connection&,
      image_type&,
      id_image_type&,
      sqlite::binding&,
      sqlite::binding&)
    {
    }
  };

  access::object_traits_impl< ::EsteeMaster, id_sqlite >::id_type
  access::object_traits_impl< ::EsteeMaster, id_sqlite >::
  id (const id_image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        id,
        i.id_value,
        i.id_size,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::EsteeMaster, id_sqlite >::id_type
  access::object_traits_impl< ::EsteeMaster, id_sqlite >::
  id (const image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        id,
        i.Estee_ID_value,
        i.Estee_ID_size,
        i.Estee_ID_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::EsteeMaster, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // DataFeed_Ticker
    //
    if (t[0UL])
    {
      i.DataFeed_Ticker_value.capacity (i.DataFeed_Ticker_size);
      grew = true;
    }

    // Underlying_Ticker
    //
    if (t[1UL])
    {
      i.Underlying_Ticker_value.capacity (i.Underlying_Ticker_size);
      grew = true;
    }

    // ISIN
    //
    if (t[2UL])
    {
      i.ISIN_value.capacity (i.ISIN_size);
      grew = true;
    }

    // Exchange_Code
    //
    if (t[3UL])
    {
      i.Exchange_Code_value.capacity (i.Exchange_Code_size);
      grew = true;
    }

    // Option_Type
    //
    if (t[4UL])
    {
      i.Option_Type_value.capacity (i.Option_Type_size);
      grew = true;
    }

    // Status
    //
    if (t[5UL])
    {
      i.Status_value.capacity (i.Status_size);
      grew = true;
    }

    // TOKEN2
    //
    if (t[6UL])
    {
      i.TOKEN2_value.capacity (i.TOKEN2_size);
      grew = true;
    }

    // Expiry_Date2
    //
    if (t[7UL])
    {
      i.Expiry_Date2_value.capacity (i.Expiry_Date2_size);
      grew = true;
    }

    // SERIES
    //
    if (t[8UL])
    {
      i.SERIES_value.capacity (i.SERIES_size);
      grew = true;
    }

    // Source
    //
    if (t[9UL])
    {
      i.Source_value.capacity (i.Source_size);
      grew = true;
    }

    // UnderlyingEstee_Id
    //
    if (t[10UL])
    {
      i.UnderlyingEstee_Id_value.capacity (i.UnderlyingEstee_Id_size);
      grew = true;
    }

    // Strike_Price
    //
    t[11UL] = false;

    // Tick_Size
    //
    t[12UL] = false;

    // Lot_Size
    //
    t[13UL] = false;

    // Security_Type
    //
    t[14UL] = false;

    // Token
    //
    t[15UL] = false;

    // Quote_Size
    //
    t[16UL] = false;

    // Instrument_Type
    //
    t[17UL] = false;

    // TradingCurrency
    //
    t[18UL] = false;

    // SettlementCurrency
    //
    t[19UL] = false;

    // TickSizeSlabId
    //
    t[20UL] = false;

    // AsOfDate
    //
    if (t[21UL])
    {
      i.AsOfDate_value.capacity (i.AsOfDate_size);
      grew = true;
    }

    // Last_update_time
    //
    if (t[22UL])
    {
      i.Last_update_time_value.capacity (i.Last_update_time_size);
      grew = true;
    }

    // Expiry_Date
    //
    if (t[23UL])
    {
      i.Expiry_Date_value.capacity (i.Expiry_Date_size);
      grew = true;
    }

    // SettlementDate
    //
    if (t[24UL])
    {
      i.SettlementDate_value.capacity (i.SettlementDate_size);
      grew = true;
    }

    // TradingStartDate
    //
    if (t[25UL])
    {
      i.TradingStartDate_value.capacity (i.TradingStartDate_size);
      grew = true;
    }

    // LastTradingDate
    //
    if (t[26UL])
    {
      i.LastTradingDate_value.capacity (i.LastTradingDate_size);
      grew = true;
    }

    // Estee_ID
    //
    if (t[27UL])
    {
      i.Estee_ID_value.capacity (i.Estee_ID_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::EsteeMaster, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // DataFeed_Ticker
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.DataFeed_Ticker_value.data ();
    b[n].size = &i.DataFeed_Ticker_size;
    b[n].capacity = i.DataFeed_Ticker_value.capacity ();
    b[n].is_null = &i.DataFeed_Ticker_null;
    n++;

    // Underlying_Ticker
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.Underlying_Ticker_value.data ();
    b[n].size = &i.Underlying_Ticker_size;
    b[n].capacity = i.Underlying_Ticker_value.capacity ();
    b[n].is_null = &i.Underlying_Ticker_null;
    n++;

    // ISIN
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.ISIN_value.data ();
    b[n].size = &i.ISIN_size;
    b[n].capacity = i.ISIN_value.capacity ();
    b[n].is_null = &i.ISIN_null;
    n++;

    // Exchange_Code
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.Exchange_Code_value.data ();
    b[n].size = &i.Exchange_Code_size;
    b[n].capacity = i.Exchange_Code_value.capacity ();
    b[n].is_null = &i.Exchange_Code_null;
    n++;

    // Option_Type
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.Option_Type_value.data ();
    b[n].size = &i.Option_Type_size;
    b[n].capacity = i.Option_Type_value.capacity ();
    b[n].is_null = &i.Option_Type_null;
    n++;

    // Status
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.Status_value.data ();
    b[n].size = &i.Status_size;
    b[n].capacity = i.Status_value.capacity ();
    b[n].is_null = &i.Status_null;
    n++;

    // TOKEN2
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.TOKEN2_value.data ();
    b[n].size = &i.TOKEN2_size;
    b[n].capacity = i.TOKEN2_value.capacity ();
    b[n].is_null = &i.TOKEN2_null;
    n++;

    // Expiry_Date2
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.Expiry_Date2_value.data ();
    b[n].size = &i.Expiry_Date2_size;
    b[n].capacity = i.Expiry_Date2_value.capacity ();
    b[n].is_null = &i.Expiry_Date2_null;
    n++;

    // SERIES
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.SERIES_value.data ();
    b[n].size = &i.SERIES_size;
    b[n].capacity = i.SERIES_value.capacity ();
    b[n].is_null = &i.SERIES_null;
    n++;

    // Source
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.Source_value.data ();
    b[n].size = &i.Source_size;
    b[n].capacity = i.Source_value.capacity ();
    b[n].is_null = &i.Source_null;
    n++;

    // UnderlyingEstee_Id
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.UnderlyingEstee_Id_value.data ();
    b[n].size = &i.UnderlyingEstee_Id_size;
    b[n].capacity = i.UnderlyingEstee_Id_value.capacity ();
    b[n].is_null = &i.UnderlyingEstee_Id_null;
    n++;

    // Strike_Price
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.Strike_Price_value;
    b[n].is_null = &i.Strike_Price_null;
    n++;

    // Tick_Size
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.Tick_Size_value;
    b[n].is_null = &i.Tick_Size_null;
    n++;

    // Lot_Size
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.Lot_Size_value;
    b[n].is_null = &i.Lot_Size_null;
    n++;

    // Security_Type
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.Security_Type_value;
    b[n].is_null = &i.Security_Type_null;
    n++;

    // Token
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.Token_value;
    b[n].is_null = &i.Token_null;
    n++;

    // Quote_Size
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.Quote_Size_value;
    b[n].is_null = &i.Quote_Size_null;
    n++;

    // Instrument_Type
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.Instrument_Type_value;
    b[n].is_null = &i.Instrument_Type_null;
    n++;

    // TradingCurrency
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.TradingCurrency_value;
    b[n].is_null = &i.TradingCurrency_null;
    n++;

    // SettlementCurrency
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.SettlementCurrency_value;
    b[n].is_null = &i.SettlementCurrency_null;
    n++;

    // TickSizeSlabId
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.TickSizeSlabId_value;
    b[n].is_null = &i.TickSizeSlabId_null;
    n++;

    // AsOfDate
    //
    b[n].type = sqlite::image_traits<
      ::boost::posix_time::ptime,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.AsOfDate_value.data ();
    b[n].size = &i.AsOfDate_size;
    b[n].capacity = i.AsOfDate_value.capacity ();
    b[n].is_null = &i.AsOfDate_null;
    n++;

    // Last_update_time
    //
    b[n].type = sqlite::image_traits<
      ::boost::posix_time::ptime,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.Last_update_time_value.data ();
    b[n].size = &i.Last_update_time_size;
    b[n].capacity = i.Last_update_time_value.capacity ();
    b[n].is_null = &i.Last_update_time_null;
    n++;

    // Expiry_Date
    //
    b[n].type = sqlite::image_traits<
      ::boost::posix_time::ptime,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.Expiry_Date_value.data ();
    b[n].size = &i.Expiry_Date_size;
    b[n].capacity = i.Expiry_Date_value.capacity ();
    b[n].is_null = &i.Expiry_Date_null;
    n++;

    // SettlementDate
    //
    b[n].type = sqlite::image_traits<
      ::boost::posix_time::ptime,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.SettlementDate_value.data ();
    b[n].size = &i.SettlementDate_size;
    b[n].capacity = i.SettlementDate_value.capacity ();
    b[n].is_null = &i.SettlementDate_null;
    n++;

    // TradingStartDate
    //
    b[n].type = sqlite::image_traits<
      ::boost::posix_time::ptime,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.TradingStartDate_value.data ();
    b[n].size = &i.TradingStartDate_size;
    b[n].capacity = i.TradingStartDate_value.capacity ();
    b[n].is_null = &i.TradingStartDate_null;
    n++;

    // LastTradingDate
    //
    b[n].type = sqlite::image_traits<
      ::boost::posix_time::ptime,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.LastTradingDate_value.data ();
    b[n].size = &i.LastTradingDate_size;
    b[n].capacity = i.LastTradingDate_value.capacity ();
    b[n].is_null = &i.LastTradingDate_null;
    n++;

    // Estee_ID
    //
    if (sk != statement_update)
    {
      b[n].type = sqlite::image_traits<
        ::std::string,
        sqlite::id_text>::bind_value;
      b[n].buffer = i.Estee_ID_value.data ();
      b[n].size = &i.Estee_ID_size;
      b[n].capacity = i.Estee_ID_value.capacity ();
      b[n].is_null = &i.Estee_ID_null;
      n++;
    }
  }

  void access::object_traits_impl< ::EsteeMaster, id_sqlite >::
  bind (sqlite::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.id_value.data ();
    b[n].size = &i.id_size;
    b[n].capacity = i.id_value.capacity ();
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::EsteeMaster, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // DataFeed_Ticker
    //
    {
      ::std::string const& v =
        o.DataFeed_Ticker;

      bool is_null (false);
      std::size_t cap (i.DataFeed_Ticker_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.DataFeed_Ticker_value,
        i.DataFeed_Ticker_size,
        is_null,
        v);
      i.DataFeed_Ticker_null = is_null;
      grew = grew || (cap != i.DataFeed_Ticker_value.capacity ());
    }

    // Underlying_Ticker
    //
    {
      ::std::string const& v =
        o.Underlying_Ticker;

      bool is_null (false);
      std::size_t cap (i.Underlying_Ticker_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.Underlying_Ticker_value,
        i.Underlying_Ticker_size,
        is_null,
        v);
      i.Underlying_Ticker_null = is_null;
      grew = grew || (cap != i.Underlying_Ticker_value.capacity ());
    }

    // ISIN
    //
    {
      ::std::string const& v =
        o.ISIN;

      bool is_null (false);
      std::size_t cap (i.ISIN_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.ISIN_value,
        i.ISIN_size,
        is_null,
        v);
      i.ISIN_null = is_null;
      grew = grew || (cap != i.ISIN_value.capacity ());
    }

    // Exchange_Code
    //
    {
      ::std::string const& v =
        o.Exchange_Code;

      bool is_null (false);
      std::size_t cap (i.Exchange_Code_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.Exchange_Code_value,
        i.Exchange_Code_size,
        is_null,
        v);
      i.Exchange_Code_null = is_null;
      grew = grew || (cap != i.Exchange_Code_value.capacity ());
    }

    // Option_Type
    //
    {
      ::std::string const& v =
        o.Option_Type;

      bool is_null (false);
      std::size_t cap (i.Option_Type_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.Option_Type_value,
        i.Option_Type_size,
        is_null,
        v);
      i.Option_Type_null = is_null;
      grew = grew || (cap != i.Option_Type_value.capacity ());
    }

    // Status
    //
    {
      ::std::string const& v =
        o.Status;

      bool is_null (false);
      std::size_t cap (i.Status_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.Status_value,
        i.Status_size,
        is_null,
        v);
      i.Status_null = is_null;
      grew = grew || (cap != i.Status_value.capacity ());
    }

    // TOKEN2
    //
    {
      ::std::string const& v =
        o.TOKEN2;

      bool is_null (false);
      std::size_t cap (i.TOKEN2_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.TOKEN2_value,
        i.TOKEN2_size,
        is_null,
        v);
      i.TOKEN2_null = is_null;
      grew = grew || (cap != i.TOKEN2_value.capacity ());
    }

    // Expiry_Date2
    //
    {
      ::std::string const& v =
        o.Expiry_Date2;

      bool is_null (false);
      std::size_t cap (i.Expiry_Date2_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.Expiry_Date2_value,
        i.Expiry_Date2_size,
        is_null,
        v);
      i.Expiry_Date2_null = is_null;
      grew = grew || (cap != i.Expiry_Date2_value.capacity ());
    }

    // SERIES
    //
    {
      ::std::string const& v =
        o.SERIES;

      bool is_null (false);
      std::size_t cap (i.SERIES_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.SERIES_value,
        i.SERIES_size,
        is_null,
        v);
      i.SERIES_null = is_null;
      grew = grew || (cap != i.SERIES_value.capacity ());
    }

    // Source
    //
    {
      ::std::string const& v =
        o.Source;

      bool is_null (false);
      std::size_t cap (i.Source_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.Source_value,
        i.Source_size,
        is_null,
        v);
      i.Source_null = is_null;
      grew = grew || (cap != i.Source_value.capacity ());
    }

    // UnderlyingEstee_Id
    //
    {
      ::std::string const& v =
        o.UnderlyingEstee_Id;

      bool is_null (false);
      std::size_t cap (i.UnderlyingEstee_Id_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.UnderlyingEstee_Id_value,
        i.UnderlyingEstee_Id_size,
        is_null,
        v);
      i.UnderlyingEstee_Id_null = is_null;
      grew = grew || (cap != i.UnderlyingEstee_Id_value.capacity ());
    }

    // Strike_Price
    //
    {
      double const& v =
        o.Strike_Price;

      bool is_null (true);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.Strike_Price_value,
        is_null,
        v);
      i.Strike_Price_null = is_null;
    }

    // Tick_Size
    //
    {
      double const& v =
        o.Tick_Size;

      bool is_null (true);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i.Tick_Size_value,
        is_null,
        v);
      i.Tick_Size_null = is_null;
    }

    // Lot_Size
    //
    {
      int const& v =
        o.Lot_Size;

      bool is_null (false);
      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_image (
        i.Lot_Size_value,
        is_null,
        v);
      i.Lot_Size_null = is_null;
    }

    // Security_Type
    //
    {
      int const& v =
        o.Security_Type;

      bool is_null (false);
      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_image (
        i.Security_Type_value,
        is_null,
        v);
      i.Security_Type_null = is_null;
    }

    // Token
    //
    {
      int const& v =
        o.Token;

      bool is_null (false);
      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_image (
        i.Token_value,
        is_null,
        v);
      i.Token_null = is_null;
    }

    // Quote_Size
    //
    {
      int const& v =
        o.Quote_Size;

      bool is_null (false);
      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_image (
        i.Quote_Size_value,
        is_null,
        v);
      i.Quote_Size_null = is_null;
    }

    // Instrument_Type
    //
    {
      int const& v =
        o.Instrument_Type;

      bool is_null (false);
      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_image (
        i.Instrument_Type_value,
        is_null,
        v);
      i.Instrument_Type_null = is_null;
    }

    // TradingCurrency
    //
    {
      int const& v =
        o.TradingCurrency;

      bool is_null (false);
      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_image (
        i.TradingCurrency_value,
        is_null,
        v);
      i.TradingCurrency_null = is_null;
    }

    // SettlementCurrency
    //
    {
      int const& v =
        o.SettlementCurrency;

      bool is_null (false);
      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_image (
        i.SettlementCurrency_value,
        is_null,
        v);
      i.SettlementCurrency_null = is_null;
    }

    // TickSizeSlabId
    //
    {
      int const& v =
        o.TickSizeSlabId;

      bool is_null (false);
      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_image (
        i.TickSizeSlabId_value,
        is_null,
        v);
      i.TickSizeSlabId_null = is_null;
    }

    // AsOfDate
    //
    {
      ::boost::posix_time::ptime const& v =
        o.AsOfDate;

      bool is_null (true);
      std::size_t cap (i.AsOfDate_value.capacity ());
      sqlite::value_traits<
          ::boost::posix_time::ptime,
          sqlite::id_text >::set_image (
        i.AsOfDate_value,
        i.AsOfDate_size,
        is_null,
        v);
      i.AsOfDate_null = is_null;
      grew = grew || (cap != i.AsOfDate_value.capacity ());
    }

    // Last_update_time
    //
    {
      ::boost::posix_time::ptime const& v =
        o.Last_update_time;

      bool is_null (true);
      std::size_t cap (i.Last_update_time_value.capacity ());
      sqlite::value_traits<
          ::boost::posix_time::ptime,
          sqlite::id_text >::set_image (
        i.Last_update_time_value,
        i.Last_update_time_size,
        is_null,
        v);
      i.Last_update_time_null = is_null;
      grew = grew || (cap != i.Last_update_time_value.capacity ());
    }

    // Expiry_Date
    //
    {
      ::boost::posix_time::ptime const& v =
        o.Expiry_Date;

      bool is_null (true);
      std::size_t cap (i.Expiry_Date_value.capacity ());
      sqlite::value_traits<
          ::boost::posix_time::ptime,
          sqlite::id_text >::set_image (
        i.Expiry_Date_value,
        i.Expiry_Date_size,
        is_null,
        v);
      i.Expiry_Date_null = is_null;
      grew = grew || (cap != i.Expiry_Date_value.capacity ());
    }

    // SettlementDate
    //
    {
      ::boost::posix_time::ptime const& v =
        o.SettlementDate;

      bool is_null (true);
      std::size_t cap (i.SettlementDate_value.capacity ());
      sqlite::value_traits<
          ::boost::posix_time::ptime,
          sqlite::id_text >::set_image (
        i.SettlementDate_value,
        i.SettlementDate_size,
        is_null,
        v);
      i.SettlementDate_null = is_null;
      grew = grew || (cap != i.SettlementDate_value.capacity ());
    }

    // TradingStartDate
    //
    {
      ::boost::posix_time::ptime const& v =
        o.TradingStartDate;

      bool is_null (true);
      std::size_t cap (i.TradingStartDate_value.capacity ());
      sqlite::value_traits<
          ::boost::posix_time::ptime,
          sqlite::id_text >::set_image (
        i.TradingStartDate_value,
        i.TradingStartDate_size,
        is_null,
        v);
      i.TradingStartDate_null = is_null;
      grew = grew || (cap != i.TradingStartDate_value.capacity ());
    }

    // LastTradingDate
    //
    {
      ::boost::posix_time::ptime const& v =
        o.LastTradingDate;

      bool is_null (true);
      std::size_t cap (i.LastTradingDate_value.capacity ());
      sqlite::value_traits<
          ::boost::posix_time::ptime,
          sqlite::id_text >::set_image (
        i.LastTradingDate_value,
        i.LastTradingDate_size,
        is_null,
        v);
      i.LastTradingDate_null = is_null;
      grew = grew || (cap != i.LastTradingDate_value.capacity ());
    }

    // Estee_ID
    //
    if (sk == statement_insert)
    {
      ::std::string const& v =
        o.Estee_ID;

      bool is_null (false);
      std::size_t cap (i.Estee_ID_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.Estee_ID_value,
        i.Estee_ID_size,
        is_null,
        v);
      i.Estee_ID_null = is_null;
      grew = grew || (cap != i.Estee_ID_value.capacity ());
    }

    return grew;
  }

  void access::object_traits_impl< ::EsteeMaster, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // DataFeed_Ticker
    //
    {
      ::std::string& v =
        o.DataFeed_Ticker;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.DataFeed_Ticker_value,
        i.DataFeed_Ticker_size,
        i.DataFeed_Ticker_null);
    }

    // Underlying_Ticker
    //
    {
      ::std::string& v =
        o.Underlying_Ticker;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.Underlying_Ticker_value,
        i.Underlying_Ticker_size,
        i.Underlying_Ticker_null);
    }

    // ISIN
    //
    {
      ::std::string& v =
        o.ISIN;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.ISIN_value,
        i.ISIN_size,
        i.ISIN_null);
    }

    // Exchange_Code
    //
    {
      ::std::string& v =
        o.Exchange_Code;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.Exchange_Code_value,
        i.Exchange_Code_size,
        i.Exchange_Code_null);
    }

    // Option_Type
    //
    {
      ::std::string& v =
        o.Option_Type;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.Option_Type_value,
        i.Option_Type_size,
        i.Option_Type_null);
    }

    // Status
    //
    {
      ::std::string& v =
        o.Status;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.Status_value,
        i.Status_size,
        i.Status_null);
    }

    // TOKEN2
    //
    {
      ::std::string& v =
        o.TOKEN2;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.TOKEN2_value,
        i.TOKEN2_size,
        i.TOKEN2_null);
    }

    // Expiry_Date2
    //
    {
      ::std::string& v =
        o.Expiry_Date2;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.Expiry_Date2_value,
        i.Expiry_Date2_size,
        i.Expiry_Date2_null);
    }

    // SERIES
    //
    {
      ::std::string& v =
        o.SERIES;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.SERIES_value,
        i.SERIES_size,
        i.SERIES_null);
    }

    // Source
    //
    {
      ::std::string& v =
        o.Source;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.Source_value,
        i.Source_size,
        i.Source_null);
    }

    // UnderlyingEstee_Id
    //
    {
      ::std::string& v =
        o.UnderlyingEstee_Id;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.UnderlyingEstee_Id_value,
        i.UnderlyingEstee_Id_size,
        i.UnderlyingEstee_Id_null);
    }

    // Strike_Price
    //
    {
      double& v =
        o.Strike_Price;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.Strike_Price_value,
        i.Strike_Price_null);
    }

    // Tick_Size
    //
    {
      double& v =
        o.Tick_Size;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i.Tick_Size_value,
        i.Tick_Size_null);
    }

    // Lot_Size
    //
    {
      int& v =
        o.Lot_Size;

      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_value (
        v,
        i.Lot_Size_value,
        i.Lot_Size_null);
    }

    // Security_Type
    //
    {
      int& v =
        o.Security_Type;

      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_value (
        v,
        i.Security_Type_value,
        i.Security_Type_null);
    }

    // Token
    //
    {
      int& v =
        o.Token;

      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_value (
        v,
        i.Token_value,
        i.Token_null);
    }

    // Quote_Size
    //
    {
      int& v =
        o.Quote_Size;

      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_value (
        v,
        i.Quote_Size_value,
        i.Quote_Size_null);
    }

    // Instrument_Type
    //
    {
      int& v =
        o.Instrument_Type;

      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_value (
        v,
        i.Instrument_Type_value,
        i.Instrument_Type_null);
    }

    // TradingCurrency
    //
    {
      int& v =
        o.TradingCurrency;

      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_value (
        v,
        i.TradingCurrency_value,
        i.TradingCurrency_null);
    }

    // SettlementCurrency
    //
    {
      int& v =
        o.SettlementCurrency;

      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_value (
        v,
        i.SettlementCurrency_value,
        i.SettlementCurrency_null);
    }

    // TickSizeSlabId
    //
    {
      int& v =
        o.TickSizeSlabId;

      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_value (
        v,
        i.TickSizeSlabId_value,
        i.TickSizeSlabId_null);
    }

    // AsOfDate
    //
    {
      ::boost::posix_time::ptime& v =
        o.AsOfDate;

      sqlite::value_traits<
          ::boost::posix_time::ptime,
          sqlite::id_text >::set_value (
        v,
        i.AsOfDate_value,
        i.AsOfDate_size,
        i.AsOfDate_null);
    }

    // Last_update_time
    //
    {
      ::boost::posix_time::ptime& v =
        o.Last_update_time;

      sqlite::value_traits<
          ::boost::posix_time::ptime,
          sqlite::id_text >::set_value (
        v,
        i.Last_update_time_value,
        i.Last_update_time_size,
        i.Last_update_time_null);
    }

    // Expiry_Date
    //
    {
      ::boost::posix_time::ptime& v =
        o.Expiry_Date;

      sqlite::value_traits<
          ::boost::posix_time::ptime,
          sqlite::id_text >::set_value (
        v,
        i.Expiry_Date_value,
        i.Expiry_Date_size,
        i.Expiry_Date_null);
    }

    // SettlementDate
    //
    {
      ::boost::posix_time::ptime& v =
        o.SettlementDate;

      sqlite::value_traits<
          ::boost::posix_time::ptime,
          sqlite::id_text >::set_value (
        v,
        i.SettlementDate_value,
        i.SettlementDate_size,
        i.SettlementDate_null);
    }

    // TradingStartDate
    //
    {
      ::boost::posix_time::ptime& v =
        o.TradingStartDate;

      sqlite::value_traits<
          ::boost::posix_time::ptime,
          sqlite::id_text >::set_value (
        v,
        i.TradingStartDate_value,
        i.TradingStartDate_size,
        i.TradingStartDate_null);
    }

    // LastTradingDate
    //
    {
      ::boost::posix_time::ptime& v =
        o.LastTradingDate;

      sqlite::value_traits<
          ::boost::posix_time::ptime,
          sqlite::id_text >::set_value (
        v,
        i.LastTradingDate_value,
        i.LastTradingDate_size,
        i.LastTradingDate_null);
    }

    // Estee_ID
    //
    {
      ::std::string& v =
        o.Estee_ID;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.Estee_ID_value,
        i.Estee_ID_size,
        i.Estee_ID_null);
    }
  }

  void access::object_traits_impl< ::EsteeMaster, id_sqlite >::
  init (id_image_type& i, const id_type& id)
  {
    bool grew (false);
    {
      bool is_null (false);
      std::size_t cap (i.id_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.id_value,
        i.id_size,
        is_null,
        id);
      i.id_null = is_null;
      grew = grew || (cap != i.id_value.capacity ());
    }

    if (grew)
      i.version++;
  }

  const char access::object_traits_impl< ::EsteeMaster, id_sqlite >::persist_statement[] =
  "INSERT INTO \"EsteeMaster\" "
  "(\"DataFeed_Ticker\", "
  "\"Underlying_Ticker\", "
  "\"ISIN\", "
  "\"Exchange_Code\", "
  "\"Option_Type\", "
  "\"Status\", "
  "\"TOKEN2\", "
  "\"Expiry_Date2\", "
  "\"SERIES\", "
  "\"Source\", "
  "\"UnderlyingEstee_Id\", "
  "\"Strike_Price\", "
  "\"Tick_Size\", "
  "\"Lot_Size\", "
  "\"Security_Type\", "
  "\"Token\", "
  "\"Quote_Size\", "
  "\"Instrument_Type\", "
  "\"TradingCurrency\", "
  "\"SettlementCurrency\", "
  "\"TickSizeSlabId\", "
  "\"AsOfDate\", "
  "\"Last_update_time\", "
  "\"Expiry_Date\", "
  "\"SettlementDate\", "
  "\"TradingStartDate\", "
  "\"LastTradingDate\", "
  "\"Estee_ID\") "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::EsteeMaster, id_sqlite >::find_statement[] =
  "SELECT "
  "\"EsteeMaster\".\"DataFeed_Ticker\", "
  "\"EsteeMaster\".\"Underlying_Ticker\", "
  "\"EsteeMaster\".\"ISIN\", "
  "\"EsteeMaster\".\"Exchange_Code\", "
  "\"EsteeMaster\".\"Option_Type\", "
  "\"EsteeMaster\".\"Status\", "
  "\"EsteeMaster\".\"TOKEN2\", "
  "\"EsteeMaster\".\"Expiry_Date2\", "
  "\"EsteeMaster\".\"SERIES\", "
  "\"EsteeMaster\".\"Source\", "
  "\"EsteeMaster\".\"UnderlyingEstee_Id\", "
  "\"EsteeMaster\".\"Strike_Price\", "
  "\"EsteeMaster\".\"Tick_Size\", "
  "\"EsteeMaster\".\"Lot_Size\", "
  "\"EsteeMaster\".\"Security_Type\", "
  "\"EsteeMaster\".\"Token\", "
  "\"EsteeMaster\".\"Quote_Size\", "
  "\"EsteeMaster\".\"Instrument_Type\", "
  "\"EsteeMaster\".\"TradingCurrency\", "
  "\"EsteeMaster\".\"SettlementCurrency\", "
  "\"EsteeMaster\".\"TickSizeSlabId\", "
  "\"EsteeMaster\".\"AsOfDate\", "
  "\"EsteeMaster\".\"Last_update_time\", "
  "\"EsteeMaster\".\"Expiry_Date\", "
  "\"EsteeMaster\".\"SettlementDate\", "
  "\"EsteeMaster\".\"TradingStartDate\", "
  "\"EsteeMaster\".\"LastTradingDate\", "
  "\"EsteeMaster\".\"Estee_ID\" "
  "FROM \"EsteeMaster\" "
  "WHERE \"EsteeMaster\".\"Estee_ID\"=?";

  const char access::object_traits_impl< ::EsteeMaster, id_sqlite >::update_statement[] =
  "UPDATE \"EsteeMaster\" "
  "SET "
  "\"DataFeed_Ticker\"=?, "
  "\"Underlying_Ticker\"=?, "
  "\"ISIN\"=?, "
  "\"Exchange_Code\"=?, "
  "\"Option_Type\"=?, "
  "\"Status\"=?, "
  "\"TOKEN2\"=?, "
  "\"Expiry_Date2\"=?, "
  "\"SERIES\"=?, "
  "\"Source\"=?, "
  "\"UnderlyingEstee_Id\"=?, "
  "\"Strike_Price\"=?, "
  "\"Tick_Size\"=?, "
  "\"Lot_Size\"=?, "
  "\"Security_Type\"=?, "
  "\"Token\"=?, "
  "\"Quote_Size\"=?, "
  "\"Instrument_Type\"=?, "
  "\"TradingCurrency\"=?, "
  "\"SettlementCurrency\"=?, "
  "\"TickSizeSlabId\"=?, "
  "\"AsOfDate\"=?, "
  "\"Last_update_time\"=?, "
  "\"Expiry_Date\"=?, "
  "\"SettlementDate\"=?, "
  "\"TradingStartDate\"=?, "
  "\"LastTradingDate\"=? "
  "WHERE \"Estee_ID\"=?";

  const char access::object_traits_impl< ::EsteeMaster, id_sqlite >::erase_statement[] =
  "DELETE FROM \"EsteeMaster\" "
  "WHERE \"Estee_ID\"=?";

  const char access::object_traits_impl< ::EsteeMaster, id_sqlite >::query_statement[] =
  "SELECT "
  "\"EsteeMaster\".\"DataFeed_Ticker\", "
  "\"EsteeMaster\".\"Underlying_Ticker\", "
  "\"EsteeMaster\".\"ISIN\", "
  "\"EsteeMaster\".\"Exchange_Code\", "
  "\"EsteeMaster\".\"Option_Type\", "
  "\"EsteeMaster\".\"Status\", "
  "\"EsteeMaster\".\"TOKEN2\", "
  "\"EsteeMaster\".\"Expiry_Date2\", "
  "\"EsteeMaster\".\"SERIES\", "
  "\"EsteeMaster\".\"Source\", "
  "\"EsteeMaster\".\"UnderlyingEstee_Id\", "
  "\"EsteeMaster\".\"Strike_Price\", "
  "\"EsteeMaster\".\"Tick_Size\", "
  "\"EsteeMaster\".\"Lot_Size\", "
  "\"EsteeMaster\".\"Security_Type\", "
  "\"EsteeMaster\".\"Token\", "
  "\"EsteeMaster\".\"Quote_Size\", "
  "\"EsteeMaster\".\"Instrument_Type\", "
  "\"EsteeMaster\".\"TradingCurrency\", "
  "\"EsteeMaster\".\"SettlementCurrency\", "
  "\"EsteeMaster\".\"TickSizeSlabId\", "
  "\"EsteeMaster\".\"AsOfDate\", "
  "\"EsteeMaster\".\"Last_update_time\", "
  "\"EsteeMaster\".\"Expiry_Date\", "
  "\"EsteeMaster\".\"SettlementDate\", "
  "\"EsteeMaster\".\"TradingStartDate\", "
  "\"EsteeMaster\".\"LastTradingDate\", "
  "\"EsteeMaster\".\"Estee_ID\" "
  "FROM \"EsteeMaster\"";

  const char access::object_traits_impl< ::EsteeMaster, id_sqlite >::erase_query_statement[] =
  "DELETE FROM \"EsteeMaster\"";

  const char access::object_traits_impl< ::EsteeMaster, id_sqlite >::table_name[] =
  "\"EsteeMaster\"";

  void access::object_traits_impl< ::EsteeMaster, id_sqlite >::
  persist (database& db, object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    im.Estee_ID_null = true;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.Estee_ID = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::EsteeMaster, id_sqlite >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;
    using sqlite::update_statement;

    callback (db, obj, callback_event::pre_update);

    sqlite::transaction& tr (sqlite::transaction::current ());
    sqlite::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.Estee_ID);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::EsteeMaster, id_sqlite >::
  erase (database& db, const id_type& id)
  {
    using namespace sqlite;

    ODB_POTENTIALLY_UNUSED (db);

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::EsteeMaster, id_sqlite >::pointer_type
  access::object_traits_impl< ::EsteeMaster, id_sqlite >::
  find (database& db, const id_type& id)
  {
    using namespace sqlite;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::EsteeMaster, id_sqlite >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::EsteeMaster, id_sqlite >::
  reload (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.Estee_ID);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::EsteeMaster, id_sqlite >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace sqlite;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::EsteeMaster, id_sqlite >::object_type >
  access::object_traits_impl< ::EsteeMaster, id_sqlite >::
  query (database&, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) sqlite::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  result< access::object_traits_impl< ::EsteeMaster, id_sqlite >::object_type >
  access::object_traits_impl< ::EsteeMaster, id_sqlite >::
  query (database& db, const odb::query_base& q)
  {
    return query (db, query_base_type (q));
  }

  unsigned long long access::object_traits_impl< ::EsteeMaster, id_sqlite >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }

  unsigned long long access::object_traits_impl< ::EsteeMaster, id_sqlite >::
  erase_query (database& db, const odb::query_base& q)
  {
    return erase_query (db, query_base_type (q));
  }

  static const
  access::object_traits_impl< ::EsteeMaster, id_common >::
  function_table_type function_table_EsteeMaster_ =
  {
    &access::object_traits_impl< ::EsteeMaster, id_sqlite >::persist,
    &access::object_traits_impl< ::EsteeMaster, id_sqlite >::find,
    &access::object_traits_impl< ::EsteeMaster, id_sqlite >::find,
    &access::object_traits_impl< ::EsteeMaster, id_sqlite >::reload,
    &access::object_traits_impl< ::EsteeMaster, id_sqlite >::update,
    &access::object_traits_impl< ::EsteeMaster, id_sqlite >::erase,
    &access::object_traits_impl< ::EsteeMaster, id_sqlite >::erase,
    &access::object_traits_impl< ::EsteeMaster, id_sqlite >::query,
    &access::object_traits_impl< ::EsteeMaster, id_sqlite >::erase_query
  };

  static const object_function_table_entry< ::EsteeMaster, id_sqlite >
  function_table_entry_EsteeMaster_ (
    &function_table_EsteeMaster_);
}

namespace odb
{
  static bool
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);
    ODB_POTENTIALLY_UNUSED (drop);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          return true;
        }
        case 2:
        {
          db.execute ("DROP TABLE IF EXISTS \"EsteeMaster\"");
          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE \"EsteeMaster\" (\n"
                      "  \"DataFeed_Ticker\" TEXT NOT NULL,\n"
                      "  \"Underlying_Ticker\" TEXT NOT NULL,\n"
                      "  \"ISIN\" TEXT NOT NULL,\n"
                      "  \"Exchange_Code\" TEXT NOT NULL,\n"
                      "  \"Option_Type\" TEXT NOT NULL,\n"
                      "  \"Status\" TEXT NOT NULL,\n"
                      "  \"TOKEN2\" TEXT NOT NULL,\n"
                      "  \"Expiry_Date2\" TEXT NOT NULL,\n"
                      "  \"SERIES\" TEXT NOT NULL,\n"
                      "  \"Source\" TEXT NOT NULL,\n"
                      "  \"UnderlyingEstee_Id\" TEXT NOT NULL,\n"
                      "  \"Strike_Price\" REAL NULL,\n"
                      "  \"Tick_Size\" REAL NULL,\n"
                      "  \"Lot_Size\" INTEGER NOT NULL,\n"
                      "  \"Security_Type\" INTEGER NOT NULL,\n"
                      "  \"Token\" INTEGER NOT NULL,\n"
                      "  \"Quote_Size\" INTEGER NOT NULL,\n"
                      "  \"Instrument_Type\" INTEGER NOT NULL,\n"
                      "  \"TradingCurrency\" INTEGER NOT NULL,\n"
                      "  \"SettlementCurrency\" INTEGER NOT NULL,\n"
                      "  \"TickSizeSlabId\" INTEGER NOT NULL,\n"
                      "  \"AsOfDate\" DATETIME NULL,\n"
                      "  \"Last_update_time\" DATETIME NULL,\n"
                      "  \"Expiry_Date\" DATETIME NULL,\n"
                      "  \"SettlementDate\" DATETIME NULL,\n"
                      "  \"TradingStartDate\" DATETIME NULL,\n"
                      "  \"LastTradingDate\" DATETIME NULL,\n"
                      "  \"Estee_ID\" TEXT NOT NULL PRIMARY KEY AUTOINCREMENT)");
          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_create_entry
  create_schema_entry_ (
    id_sqlite,
    "",
    &create_schema);
}

#include <odb/post.hxx>
