// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#define ODB_SQLITE_QUERY_COLUMNS_DEF
#include "EsteeMasterArchive-odb-sqlite.hxx"
#undef ODB_SQLITE_QUERY_COLUMNS_DEF

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/schema-catalog-impl.hxx>
#include <odb/function-table.hxx>

#include <odb/sqlite/traits.hxx>
#include <odb/sqlite/database.hxx>
#include <odb/sqlite/transaction.hxx>
#include <odb/sqlite/connection.hxx>
#include <odb/sqlite/statement.hxx>
#include <odb/sqlite/statement-cache.hxx>
#include <odb/sqlite/simple-object-statements.hxx>
#include <odb/sqlite/container-statements.hxx>
#include <odb/sqlite/exceptions.hxx>
#include <odb/sqlite/simple-object-result.hxx>

namespace odb
{
  // EsteeMaster_Archive
  //

  template struct query_columns<
    ::EsteeMaster,
    id_sqlite,
    access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite > >;

  template struct query_columns<
    ::EsteeMaster_Archive,
    id_sqlite,
    access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite > >;

  struct access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      sqlite::connection&,
      image_type&,
      id_image_type&,
      sqlite::binding&,
      sqlite::binding&)
    {
    }
  };

  bool access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // EsteeMaster base
    //
    if (object_traits_impl< ::EsteeMaster, id_sqlite >::grow (
          i, t + 0UL))
      grew = true;

    // ID
    //
    t[28UL] = false;

    return grew;
  }

  void access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // EsteeMaster base
    //
    object_traits_impl< ::EsteeMaster, id_sqlite >::bind (b + n, i, sk);
    n += sk == statement_update ? 27UL : 28UL;

    // ID
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.ID_value;
    b[n].is_null = &i.ID_null;
    n++;
  }

  bool access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // EsteeMaster base
    //
    if (object_traits_impl< ::EsteeMaster, id_sqlite >::init (i, o, sk))
      grew = true;

    // ID
    //
    {
      int const& v =
        o.ID;

      bool is_null (false);
      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_image (
        i.ID_value,
        is_null,
        v);
      i.ID_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // EsteeMaster base
    //
    object_traits_impl< ::EsteeMaster, id_sqlite >::init (o, i, db);

    // ID
    //
    {
      int& v =
        o.ID;

      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_value (
        v,
        i.ID_value,
        i.ID_null);
    }
  }

  const char access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::persist_statement[] =
  "INSERT INTO \"EsteeMaster_Archive\" "
  "(\"DataFeed_Ticker\", "
  "\"Underlying_Ticker\", "
  "\"ISIN\", "
  "\"Exchange_Code\", "
  "\"Option_Type\", "
  "\"Status\", "
  "\"TOKEN2\", "
  "\"Expiry_Date2\", "
  "\"SERIES\", "
  "\"Source\", "
  "\"UnderlyingEstee_Id\", "
  "\"Strike_Price\", "
  "\"Tick_Size\", "
  "\"Lot_Size\", "
  "\"Security_Type\", "
  "\"Token\", "
  "\"Quote_Size\", "
  "\"Instrument_Type\", "
  "\"TradingCurrency\", "
  "\"SettlementCurrency\", "
  "\"TickSizeSlabId\", "
  "\"AsOfDate\", "
  "\"Last_update_time\", "
  "\"Expiry_Date\", "
  "\"SettlementDate\", "
  "\"TradingStartDate\", "
  "\"LastTradingDate\", "
  "\"Estee_ID\", "
  "\"ID\") "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::find_statement[] =
  "SELECT "
  "\"EsteeMaster_Archive\".\"DataFeed_Ticker\", "
  "\"EsteeMaster_Archive\".\"Underlying_Ticker\", "
  "\"EsteeMaster_Archive\".\"ISIN\", "
  "\"EsteeMaster_Archive\".\"Exchange_Code\", "
  "\"EsteeMaster_Archive\".\"Option_Type\", "
  "\"EsteeMaster_Archive\".\"Status\", "
  "\"EsteeMaster_Archive\".\"TOKEN2\", "
  "\"EsteeMaster_Archive\".\"Expiry_Date2\", "
  "\"EsteeMaster_Archive\".\"SERIES\", "
  "\"EsteeMaster_Archive\".\"Source\", "
  "\"EsteeMaster_Archive\".\"UnderlyingEstee_Id\", "
  "\"EsteeMaster_Archive\".\"Strike_Price\", "
  "\"EsteeMaster_Archive\".\"Tick_Size\", "
  "\"EsteeMaster_Archive\".\"Lot_Size\", "
  "\"EsteeMaster_Archive\".\"Security_Type\", "
  "\"EsteeMaster_Archive\".\"Token\", "
  "\"EsteeMaster_Archive\".\"Quote_Size\", "
  "\"EsteeMaster_Archive\".\"Instrument_Type\", "
  "\"EsteeMaster_Archive\".\"TradingCurrency\", "
  "\"EsteeMaster_Archive\".\"SettlementCurrency\", "
  "\"EsteeMaster_Archive\".\"TickSizeSlabId\", "
  "\"EsteeMaster_Archive\".\"AsOfDate\", "
  "\"EsteeMaster_Archive\".\"Last_update_time\", "
  "\"EsteeMaster_Archive\".\"Expiry_Date\", "
  "\"EsteeMaster_Archive\".\"SettlementDate\", "
  "\"EsteeMaster_Archive\".\"TradingStartDate\", "
  "\"EsteeMaster_Archive\".\"LastTradingDate\", "
  "\"EsteeMaster_Archive\".\"Estee_ID\", "
  "\"EsteeMaster_Archive\".\"ID\" "
  "FROM \"EsteeMaster_Archive\" "
  "WHERE \"EsteeMaster_Archive\".\"Estee_ID\"=?";

  const char access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::update_statement[] =
  "UPDATE \"EsteeMaster_Archive\" "
  "SET "
  "\"DataFeed_Ticker\"=?, "
  "\"Underlying_Ticker\"=?, "
  "\"ISIN\"=?, "
  "\"Exchange_Code\"=?, "
  "\"Option_Type\"=?, "
  "\"Status\"=?, "
  "\"TOKEN2\"=?, "
  "\"Expiry_Date2\"=?, "
  "\"SERIES\"=?, "
  "\"Source\"=?, "
  "\"UnderlyingEstee_Id\"=?, "
  "\"Strike_Price\"=?, "
  "\"Tick_Size\"=?, "
  "\"Lot_Size\"=?, "
  "\"Security_Type\"=?, "
  "\"Token\"=?, "
  "\"Quote_Size\"=?, "
  "\"Instrument_Type\"=?, "
  "\"TradingCurrency\"=?, "
  "\"SettlementCurrency\"=?, "
  "\"TickSizeSlabId\"=?, "
  "\"AsOfDate\"=?, "
  "\"Last_update_time\"=?, "
  "\"Expiry_Date\"=?, "
  "\"SettlementDate\"=?, "
  "\"TradingStartDate\"=?, "
  "\"LastTradingDate\"=?, "
  "\"ID\"=? "
  "WHERE \"Estee_ID\"=?";

  const char access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::erase_statement[] =
  "DELETE FROM \"EsteeMaster_Archive\" "
  "WHERE \"Estee_ID\"=?";

  const char access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::query_statement[] =
  "SELECT "
  "\"EsteeMaster_Archive\".\"DataFeed_Ticker\", "
  "\"EsteeMaster_Archive\".\"Underlying_Ticker\", "
  "\"EsteeMaster_Archive\".\"ISIN\", "
  "\"EsteeMaster_Archive\".\"Exchange_Code\", "
  "\"EsteeMaster_Archive\".\"Option_Type\", "
  "\"EsteeMaster_Archive\".\"Status\", "
  "\"EsteeMaster_Archive\".\"TOKEN2\", "
  "\"EsteeMaster_Archive\".\"Expiry_Date2\", "
  "\"EsteeMaster_Archive\".\"SERIES\", "
  "\"EsteeMaster_Archive\".\"Source\", "
  "\"EsteeMaster_Archive\".\"UnderlyingEstee_Id\", "
  "\"EsteeMaster_Archive\".\"Strike_Price\", "
  "\"EsteeMaster_Archive\".\"Tick_Size\", "
  "\"EsteeMaster_Archive\".\"Lot_Size\", "
  "\"EsteeMaster_Archive\".\"Security_Type\", "
  "\"EsteeMaster_Archive\".\"Token\", "
  "\"EsteeMaster_Archive\".\"Quote_Size\", "
  "\"EsteeMaster_Archive\".\"Instrument_Type\", "
  "\"EsteeMaster_Archive\".\"TradingCurrency\", "
  "\"EsteeMaster_Archive\".\"SettlementCurrency\", "
  "\"EsteeMaster_Archive\".\"TickSizeSlabId\", "
  "\"EsteeMaster_Archive\".\"AsOfDate\", "
  "\"EsteeMaster_Archive\".\"Last_update_time\", "
  "\"EsteeMaster_Archive\".\"Expiry_Date\", "
  "\"EsteeMaster_Archive\".\"SettlementDate\", "
  "\"EsteeMaster_Archive\".\"TradingStartDate\", "
  "\"EsteeMaster_Archive\".\"LastTradingDate\", "
  "\"EsteeMaster_Archive\".\"Estee_ID\", "
  "\"EsteeMaster_Archive\".\"ID\" "
  "FROM \"EsteeMaster_Archive\"";

  const char access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::erase_query_statement[] =
  "DELETE FROM \"EsteeMaster_Archive\"";

  const char access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::table_name[] =
  "\"EsteeMaster_Archive\"";

  void access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::
  persist (database& db, object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    im.Estee_ID_null = true;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.Estee_ID = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;
    using sqlite::update_statement;

    callback (db, obj, callback_event::pre_update);

    sqlite::transaction& tr (sqlite::transaction::current ());
    sqlite::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.Estee_ID);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::
  erase (database& db, const id_type& id)
  {
    using namespace sqlite;

    ODB_POTENTIALLY_UNUSED (db);

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::pointer_type
  access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::
  find (database& db, const id_type& id)
  {
    using namespace sqlite;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::
  reload (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.Estee_ID);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace sqlite;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::object_type >
  access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::
  query (database&, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) sqlite::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  result< access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::object_type >
  access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::
  query (database& db, const odb::query_base& q)
  {
    return query (db, query_base_type (q));
  }

  unsigned long long access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }

  unsigned long long access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::
  erase_query (database& db, const odb::query_base& q)
  {
    return erase_query (db, query_base_type (q));
  }

  static const
  access::object_traits_impl< ::EsteeMaster_Archive, id_common >::
  function_table_type function_table_EsteeMaster_Archive_ =
  {
    &access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::persist,
    &access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::find,
    &access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::find,
    &access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::reload,
    &access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::update,
    &access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::erase,
    &access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::erase,
    &access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::query,
    &access::object_traits_impl< ::EsteeMaster_Archive, id_sqlite >::erase_query
  };

  static const object_function_table_entry< ::EsteeMaster_Archive, id_sqlite >
  function_table_entry_EsteeMaster_Archive_ (
    &function_table_EsteeMaster_Archive_);
}

namespace odb
{
  static bool
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);
    ODB_POTENTIALLY_UNUSED (drop);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          return true;
        }
        case 2:
        {
          db.execute ("DROP TABLE IF EXISTS \"EsteeMaster_Archive\"");
          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE \"EsteeMaster_Archive\" (\n"
                      "  \"DataFeed_Ticker\" TEXT NOT NULL,\n"
                      "  \"Underlying_Ticker\" TEXT NOT NULL,\n"
                      "  \"ISIN\" TEXT NOT NULL,\n"
                      "  \"Exchange_Code\" TEXT NOT NULL,\n"
                      "  \"Option_Type\" TEXT NOT NULL,\n"
                      "  \"Status\" TEXT NOT NULL,\n"
                      "  \"TOKEN2\" TEXT NOT NULL,\n"
                      "  \"Expiry_Date2\" TEXT NOT NULL,\n"
                      "  \"SERIES\" TEXT NOT NULL,\n"
                      "  \"Source\" TEXT NOT NULL,\n"
                      "  \"UnderlyingEstee_Id\" TEXT NOT NULL,\n"
                      "  \"Strike_Price\" REAL NULL,\n"
                      "  \"Tick_Size\" REAL NULL,\n"
                      "  \"Lot_Size\" INTEGER NOT NULL,\n"
                      "  \"Security_Type\" INTEGER NOT NULL,\n"
                      "  \"Token\" INTEGER NOT NULL,\n"
                      "  \"Quote_Size\" INTEGER NOT NULL,\n"
                      "  \"Instrument_Type\" INTEGER NOT NULL,\n"
                      "  \"TradingCurrency\" INTEGER NOT NULL,\n"
                      "  \"SettlementCurrency\" INTEGER NOT NULL,\n"
                      "  \"TickSizeSlabId\" INTEGER NOT NULL,\n"
                      "  \"AsOfDate\" DATETIME NULL,\n"
                      "  \"Last_update_time\" DATETIME NULL,\n"
                      "  \"Expiry_Date\" DATETIME NULL,\n"
                      "  \"SettlementDate\" DATETIME NULL,\n"
                      "  \"TradingStartDate\" DATETIME NULL,\n"
                      "  \"LastTradingDate\" DATETIME NULL,\n"
                      "  \"Estee_ID\" TEXT NOT NULL PRIMARY KEY AUTOINCREMENT,\n"
                      "  \"ID\" INTEGER NOT NULL)");
          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_create_entry
  create_schema_entry_ (
    id_sqlite,
    "",
    &create_schema);
}

#include <odb/post.hxx>
