/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `EsteeMaster_Archive`;

CREATE TABLE `EsteeMaster_Archive` (
  `DataFeed_Ticker` TEXT NOT NULL,
  `Underlying_Ticker` TEXT NOT NULL,
  `ISIN` TEXT NOT NULL,
  `Exchange_Code` TEXT NOT NULL,
  `Option_Type` TEXT NOT NULL,
  `Status` TEXT NOT NULL,
  `TOKEN2` TEXT NOT NULL,
  `Expiry_Date2` TEXT NOT NULL,
  `SERIES` TEXT NOT NULL,
  `Source` TEXT NOT NULL,
  `UnderlyingEstee_Id` TEXT NOT NULL,
  `Strike_Price` DOUBLE NOT NULL,
  `Tick_Size` DOUBLE NOT NULL,
  `Lot_Size` INT NOT NULL,
  `Security_Type` INT NOT NULL,
  `Token` INT NOT NULL,
  `Quote_Size` INT NOT NULL,
  `Instrument_Type` INT NOT NULL,
  `TradingCurrency` INT NOT NULL,
  `SettlementCurrency` INT NOT NULL,
  `TickSizeSlabId` INT NOT NULL,
  `AsOfDate` DATETIME NULL,
  `Last_update_time` DATETIME NULL,
  `Expiry_Date` DATETIME NULL,
  `SettlementDate` DATETIME NULL,
  `TradingStartDate` DATETIME NULL,
  `LastTradingDate` DATETIME NULL,
  `Estee_ID` VARCHAR(255) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `ID` INT NOT NULL)
 ENGINE=InnoDB;

